#  Summary Tables{#cor-tabular}

```{r, echo=FALSE, message=FALSE}
message("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ running cor_tabular report ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
```


\captionsetup{justification=raggedright,singlelinecheck=false}
```{r knitr, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
config <- config::get(config = Sys.getenv("TRIAL"))

here::i_am("cor_tabular/report.Rmd")
dats <- list.files(here::here( "cor_tabular", "output", attr(config,"config")))
if(any(grepl("Figure", dats))) {
  dats <- grep("Figure", dats, value=T)
}
```
\captionsetup[table]{}


```{r tabs, results="asis", echo=FALSE, message=FALSE, warning=FALSE}
opts <- options(knitr.kable.NA = "")
numi <- 1
for (d in dats){
base::load(here::here("cor_tabular", "output", attr(config,"config"), d))
  # d_lab <- sprintf("(%s)", substr(d, 7, nchar(d)-6)) # name always starts with "Tables"/"Figure" and ends with ".Rdata"
  cat(sprintf("\n\n## %s", substr(d, 7, nchar(d)-6)))
  
  if(any(grepl("Figure", d))){
     for (i in 1:length(tlf)) {
       
       fig <- get(names(tlf)[i]) 
       }
    
  } else {
  
  
  for (i in 1:length(tlf)) {
    
  subnum <- 0
  
  tlf_labels <- tlf[[i]]
  title_i <- tlf_labels[["table_header"]]
  # title_i <- ifelse(substr(title_i, 1, 11)=="Demographic", title_i, paste(tlf_labels[["table_header"]], d_lab))
  title_i <- gsub("_", "\\\\_",title_i)

  if (names(tlf)[i] == "tab_strtm1") {
    cat("\n\n\\newgeometry{top=0.1in, bottom=0.1in, left=1in, right=1in}")
    cat("\n\n\\begin{landscape}\n")
  }
  
  footer_i <- tlf_labels[["table_footer"]]
  tlf_args <- names(tlf_labels)
  deselect <- if ("deselect" %in% tlf_args) tlf_labels[["deselect"]] else NA
  loop <- if ("loop" %in% tlf_args) tlf_labels[["loop"]] else NA

  tab <- get(names(tlf)[i]) 
   if (is.null(tab)) next
   if (nrow(tab) == 0) next

  group_table_col <- if ("group_table_col" %in% tlf_args) {
    tlf_labels[["group_table_col"]] 
    } else NA 

  rownames(tab) <- NULL
  colnames(tab) <- gsub("%", "\\\\%", colnames(tab))
  colnames(tab) <- gsub("Baseline SARS-CoV-2", "Baseline\nSARS\\-CoV\\-2",
                        colnames(tab))
  colnames(tab) <- gsub("% Greater than 2xLLO", "% Greater than\n2 $\\\\times$ LLO", colnames(tab))
  colnames(tab) <- gsub("% Greater than 4xLLO", "% Greater than\n4 $\\\\times$ LLO", colnames(tab))                        
  
  line_sep <- if ("line_sep" %in% tlf_args) {
    tlf_labels[["line_sep"]]
  } else " "

  # cat(sprintf("\\section{%s}", title_i))
  jloop <- if (!is.na(loop)) pull(tab, !!as.name(loop)) %>% unique() else 1
  for (j in jloop) {
      subnum <- subnum + 1

      tab.j <- if (is.na(loop)) {
        tab 
      } else {
        dplyr::filter(tab, !!as.name(loop) == j)
      }
      
      tab.j <- tab.j %>% select_if(~ !all(is.na(.)))
      
      if ("pack_row" %in% tlf_args) {
        pack_row_ind <- table(droplevels(tab.j[, tlf_labels[["pack_row"]]]))  
      }

      tab.j <- mutate_all(tab.j, linebreak, align = "l")
      
      if (nrow(tab.j)==1){
        tab.j <- data.frame(t(sapply(tab.j, function(x)gsub("%", "\\\\%", x))),
                        check.names = FALSE)
      }else{
        tab.j <- data.frame(sapply(tab.j, function(x)gsub("%", "\\\\%", x)),
                        check.names = FALSE)
      }
      
      caption.j <- ifelse(!is.na(loop), sprintf("%s (%s)", ifelse(j=="Stage 2", gsub("M6", "M5", title_i), title_i), j), title_i)
      
      col_name <- if ("col_name" %in% tlf_args) {
        tlf_labels[["col_name"]]
      } else setdiff(names(tab.j), deselect)

      
      col_name.j <- if(is.data.frame(col_name)) {
        col_name[,j]
        } else col_name
      col_name.j <- col_name.j[!col_name.j %in% deselect]
      
      
      tabjk <- kable(if (is.na(deselect)) {tab.j} else {tab.j %>% select(-!!deselect)},
                     align = "l",
                     format = "latex",
                     booktabs = TRUE,
                     longtable = TRUE,
                     escape = FALSE,
                     linesep=line_sep,
                     col.names = linebreak(col_name.j, align="l"),
                    caption = caption.j
                     ) %>%
        column_spec(1, width = ifelse("col1"%in%tlf_args, tlf_labels[["col1"]],"2.7cm")) %>% 
        kable_styling(latex_options = c("repeat_header", "scale_down"), 
                      repeat_header_method = "replace") %>%
        footnote(general_title = "", general = footer_i, threeparttable = TRUE,
        escape = FALSE)
      
      if ("pack_row" %in% tlf_args) {
          tabjk <- pack_rows(tabjk, index = pack_row_ind, escape = FALSE)
        }

        if ("header_above1" %in% tlf_args) {
          # This might cause issues, check when debugging
          header_above1 <- if(is.list(tlf_labels[["header_above1"]])) {
            tlf_labels[["header_above1"]][[match(j, jloop)]]
            } else tlf_labels[["header_above1"]]
      
          tabjk <-add_header_above(tabjk, header_above1)
          }

        if ("header_above2" %in% tlf_args) {
          # This might cause issues, check when debugging
          header_above2 <- if(is.list(tlf_labels[["header_above2"]])) {
            tlf_labels[["header_above2"]][[match(j, jloop)]]
            } else tlf_labels[["header_above2"]]
      
          tabjk <-add_header_above(tabjk, header_above2)
          }
      
        if ("font_size" %in% tlf_args) {
          tabjk <- tabjk %>% kable_styling(font_size = tlf_labels[["font_size"]])
        }
    print(tabjk)
    cat("\n\n\\clearpage\n")
    }
  numi <- numi + 1
  }
}
  cat("\n\n\\end{landscape}")
  cat("\n\n\\captionsetup[table]{labelformat=default}")
  cat("\n\n\\newgeometry{margin=1in}")
  }
```
