branches:
  only:
  - master
language: r
sudo: required
cran: http://cran.rstudio.com
latex: false
pandoc: true
warnings_are_errors: false
cache:
  directories:
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"
  - "$HOME/.TinyTeX/"
r:
- 4.1.1
jobs:
  include:
  - name: Moderna CoR Report
    env:
    - REPORT_TYPE=COR
    - TRIAL=moderna_mock
    script:
    - echo "Building correlates of risk report"
    - make cor_report
  - name: Janssen Pooled CoR Report
    env:
    - REPORT_TYPE=COR
    - TRIAL=janssen_pooled_mock
    script:
    - echo "Building correlates of risk report"
    - make cor_report
apt_packages:
- libxml2-dev
- libssl-dev
- libcurl4-openssl-dev
before_install:
- sudo apt-get install -y texlive-extra-utils ghostscript
install:
- cd .. && Rscript -e "install.packages(c('here', 'tinytex'))"
- wget https://cran.r-project.org/src/contrib/Archive/renv/renv_0.14.0.tar.gz
- R CMD INSTALL renv_0.14.0.tar.gz
- echo insecure >> ~/.curlrc && Rscript -e "tinytex::install_tinytex()"
- export PATH=$HOME/bin:${PATH}
- cd $TRAVIS_BUILD_DIR && Rscript -e "renv::restore()"
before_script:
- echo "B <- 5" >> $TRAVIS_BUILD_DIR/cor_coxph/code/params.R
- echo "numPerm <- 5" >> $TRAVIS_BUILD_DIR/cor_coxph/code/params.R
- echo "B <- 5" >> $TRAVIS_BUILD_DIR/cor_nonlinear/code/params.R
- cd $TRAVIS_BUILD_DIR && Rscript -e "renv::status()"
- cd $TRAVIS_BUILD_DIR && Rscript -e "row.names(installed.packages())"
after_script:
- chmod +x _deploy_reports.sh && ./_deploy_reports.sh
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - benkeser@emory.edu
    - nh@nimahejazi.org
env:
  global:
    secure: e/tWy7TLNM5MySLkVtQU0SJ/tqe4GGLcLaOiXi9JwQnyLZ5g6+TAcghJr08DgmMvlmucqG9rq1ORrHF0T+hIL2zYsuiozS5qVKva/MV5MjRM7B28ztpaB9wBKVjBf36NZkmQEve/o8ml8BObXR37P6ZwAAV455FwwtMOH8au1lfmGwwe5ie7jW8CJSvQOjcvBUS2Pup7yh8+9bHXH/IHPi0feHlPKESJWA8fDiyfD1aiNtgWKxni7kxEiFcfBFhFCz6aE/EUy65SFmjUhwx7kHrAlKlvh9CEQ3YiRYbRf+wuEkXBD+e8/pLxAbY3+OTpuuaiMfz2LKPSIxzD41FU5TXbcIJuAGsIpGgblqKpKAW/1AGkXEKP/UeyrMXAfhkxmWwu9eEdGotYDwMHu4b0MZ6H19fi5vPK0wlbPGsrR0bEIUGRuxXJNSxRtx/ovDjZvcvZ0RhFRjapnJv6Otaj71Vxfx68SnyQ/5S0JTQSgQ7WE+ivpgxOnZ3oH/7zgqD7oZIdsrMydLDWw/WD5mSi1P1iYF+T73IqToltCIBxKRiSEJsQB9Nkfa2HJ3kJcWQt7u4iSbck6nH0lcoGVB9j0jWkCfZRkYremrgTr03zb7g4XiFaXjggdrDpFyoceOZU+omquEEFyKzMKIDFVVUEOuuIRR6r81l5jhLhSUrg45k=