branches:
  only:
  - master
language: r
sudo: required
cran: http://cran.rstudio.com
latex: false
pandoc: true
warnings_are_errors: false
cache:
  directories:
  - "$HOME/.local/share/renv"
  - "$TRAVIS_BUILD_DIR/renv/library"
  - "$HOME/.TinyTeX/"
r:
- 4.1.1
jobs:
  include:
  - name: Moderna CoR Report
    env:
    - REPORT_TYPE=COR
    - TRIAL=moderna_mock
    script:
    - echo "Building correlates of risk report"
    - make cor_report
  - name: Janssen Pooled CoR Report
    env:
    - REPORT_TYPE=COR
    - TRIAL=janssen_pooled_mock
    script:
    - echo "Building correlates of risk report"
    - make cor_report
apt_packages:
- libxml2-dev
- libssl-dev
- libcurl4-openssl-dev
before_install:
- sudo apt-get install -y texlive-extra-utils ghostscript
install:
- cd .. && Rscript -e "install.packages(c('here', 'tinytex'))"
- wget https://cran.r-project.org/src/contrib/Archive/renv/renv_0.14.0.tar.gz
- R CMD INSTALL renv_0.14.0.tar.gz
- echo insecure >> ~/.curlrc && Rscript -e "tinytex::install_tinytex()"
- export PATH=$HOME/bin:${PATH}
- cd $TRAVIS_BUILD_DIR && Rscript -e "renv::restore()"
before_script:
- echo "B <- 5" >> $TRAVIS_BUILD_DIR/cor_coxph/code/params.R
- echo "numPerm <- 5" >> $TRAVIS_BUILD_DIR/cor_coxph/code/params.R
- echo "B <- 5" >> $TRAVIS_BUILD_DIR/cor_nonlinear/code/params.R
- cd $TRAVIS_BUILD_DIR && Rscript -e "renv::status()"
- cd $TRAVIS_BUILD_DIR && Rscript -e "row.names(installed.packages())"
after_script:
- chmod +x _deploy_reports.sh && ./_deploy_reports.sh
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - benkeser@emory.edu
    - nh@nimahejazi.org
env:
  global:
    secure: xLAF6qwbJIButTHZBbRWSZpThbQ7iAdmnWHooAYek4egvmFzOvrEq/UwbYkzlmRqmgQpR4VwPiUljJGLGMScD1A/WkirpJydBxSyl7crR6XNV+BfDtJ/4tIrc5ZcOmJ9z/ViPUnVMG6bUCmthmOa7WDrzqOUko2OSKyXtZzzn/7SlsVrOFAMqZ4+tkSH/0Mt1D3oDlIELkpnUhUQ0E5zqAz+yZXysZpbQDgxXp5VPNfrDWlcHXeQq9At8ZozSxWZv7ywxwnMSo1A6PTjezmTmSW2IKGZj5GywLRKHThAATEAmcwK011vn6MzKRmM2HTWiSDCdvZUr307bHueyhx8AntmOw3pMyP9kivdqkL2uZDaBjLUG8s1pVMUR52yfGT6ZtIvZ/HPXO3VwgVHUE9RuMwcC6Aa+HtJQ7wxofcMwWRjiCPX22xwp3phq8q1LOFDHyZfBVPXQAsKlnkY2Fvhm2MWqONhW6aZyayGQY1JsZ9HB7Nj/lfPMMig8liLb6qzNVEE1hrnM2yTC2p2oLpZTuOXfJrq7sKltn/nYgQetWO2kvLmrfL9OHrpBiSCmG9ay6PMXLzvPhQ/NCz669k2IM7+lrlerCkbX7N7Ipicl1UMa/zQiWSgZiBr/OD656sk0Ok/99D7b/jLZr8ShjxkKRLRxQBla8afoaONeeUrT+Y=
