#!/bin/bash


if [ $# -eq 0 ]
  then
    echo "********* Please provide a module name, e.g. cor_coxph, as an argument."
    exit
fi



for T in  janssen_pooled_partA janssen_na_partA janssen_la_partA janssen_sa_partA
do
    export TRIAL=$T 
    echo $TRIAL
    if [[ "$1" == "cor_report" ]] 
    then
        make cor_report
    else
        make -k -C $1 all
        bash ./_build_chapter.sh $1
    fi

done
