#!/bin/bash

for T in janssen_la_realbAb janssen_la_realADCP janssen_la_realPsV
do
    export TRIAL=$T 
    echo $TRIAL
    if [[ "$1" == "cor_report" ]] 
    then
        make cor_report
    else
        make -k -C $1 all
        bash ./_build_chapter.sh $1
    fi

done
