#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "********* Please provide a module name, e.g. cor_coxph, as an argument."
    exit
fi


for T in prevent19
do
    export TRIAL=$T 
    echo $TRIAL
    make -k -C $1 all
    bash ./_build_chapter.sh $1
done
