---
title: "EMSEMBLE Stage 1 Variants-Invariant Correlates Imputation Check"
output: html_document
---
        
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survey)
library(kyotil)

dat_mapped=read.csv('/trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_PartAComplete_variant_mapped_20240226.csv')
dat_proc = read.csv('/trials/covpn/p3003/analysis/correlates/Part_A_Blinded_Phase_Data/adata/janssen_partA_VL_data_processed_20241015.csv')
assay_metadata=read.csv('~/correlates_reporting2/assay_metadata/janssen_partA_VL_assay_metadata.csv')
assays=assay_metadata$assay

country.codes=c("USA", "ARG", "BRA", "CHL", "COL", "MEX", "PER", "ZAF")
dat_mapped$cc=country.codes[dat_mapped$Country+1]
dat_proc$cc=country.codes[dat_proc$Country+1]

dat_pooled_partA = read.csv('/trials/covpn/p3003/analysis/correlates/Part_A_Blinded_Phase_Data/adata/janssen_pooled_partA_data_processed_with_riskscore.csv')

stopifnot(all(dat_pooled_partA$Ptid==dat_mapped$Ptid))
stopifnot(all(dat_proc$Ptid==dat_mapped$Ptid))

# forVariants is F if ancestral ID50 is measured before variants study, T if for variants study
dat_mapped$forVariants = ifelse(!is.na(dat_pooled_partA$Day29pseudoneutid50),F,T)

# an indicator for non-cases in the whole cohort
kp = with(dat_mapped, EventIndPrimaryIncludeNotMolecConfirmedD1 == 0)

# an indicator for cases in the whole cohort
cases= with(dat_mapped, EventIndPrimaryIncludeNotMolecConfirmedD1 == 1)
dat_proc$cases= with(dat_proc, EventIndPrimaryIncludeNotMolecConfirmedD1 == 1)
dat_mapped$ph2.D29 = dat_proc$ph2.D29
dat_mapped$cases = dat_proc$cases

# an alias for subcohort
subc = dat_mapped$SubcohortInd==1

dat_mapped$COL_variants_study = with(dat_mapped, cc=="COL" & EventIndPrimaryIncludeNotMolecConfirmedD1==0 & SubcohortInd!=1 & !is.na(Day29bindSpike_D614))
dat_mapped$SubcohortIndPlus = ifelse(dat_mapped$SubcohortInd | dat_mapped$COL_variants_study, 1, 0)
table(dat_mapped$SubcohortIndPlus, dat_mapped$SubcohortInd)
```

```{r}
tmp=subset(dat_proc, (ph2.D29variant | Trt==0) & Bserostatus==0)
mytable(tmp$wt.D29variant)

subset(dat_proc, Ptid=="VAC31518COV3001-3000137")

```

## Make analysis data for variant study exposure proximal correlates

```{r}
tmp=subset(dat_proc, ph1.D29 & Trt==1 & Bserostatus==0 & Region==1)
mytable(!is.na(tmp$Mon6bindSpike), !is.na(tmp$Mon6bindSpike_D614))
mytable(!is.na(tmp$Mon6bindSpike), !is.na(tmp$Day29bindSpike))

tmp=subset(dat_proc, ph2.D29 & Trt==1 & Bserostatus==0 & Region==1)
mytable(!is.na(tmp$Mon6bindSpike), !is.na(tmp$Mon6bindSpike_D614), tmp$EventIndPrimaryD29)
```


```{r}
tmp=subset(dat_proc, ph1.D29 & Trt==1 & Bserostatus==0 & Region==1)
mytable(!is.na(tmp$Day71bindSpike), !is.na(tmp$Day71bindSpike_D614))
mytable(!is.na(tmp$Day71bindSpike), !is.na(tmp$Day29bindSpike))

tmp=subset(dat_proc, ph2.D29 & Trt==1 & Bserostatus==0)
mytable(!is.na(tmp$Day71bindSpike), !is.na(tmp$Day71bindSpike_D614), tmp$EventIndPrimaryD29, tmp$Region)

tmp=subset(dat_proc, ph2.D29 & Trt==1 & Bserostatus==0 & Region==1 & !is.na(Day71bindSpike) & !is.na(Day71bindSpike_D614))
tmp$diff=tmp$Day71bindSpike - tmp$Day71bindSpike_D614
myboxplot(list(tmp$diff))
wilcox.test (tmp$Day71bindSpike, tmp$Day71bindSpike_D614, paired=T)
corplot(Day71bindSpike~Day71bindSpike_D614, tmp)
summary(10**tmp$diff)
```


```{r}
tmp=subset(dat_proc, ph1.D29 & Trt==1 & Bserostatus==0 & Region==1)
mytable(!is.na(tmp$Day71bindSpike), !is.na(tmp$Day71bindSpike_D614))
mytable(!is.na(tmp$Day71bindSpike), !is.na(tmp$Day29bindSpike))

tmp=subset(dat_proc, ph2.D29 & Trt==1 & Bserostatus==0 & Region==1)
mytable(!is.na(tmp$Day71bindSpike), !is.na(tmp$Day71bindSpike_D614), tmp$EventIndPrimaryD29)

tmp=subset(dat_proc, ph2.D29 & Trt==1 & Bserostatus==0 & Region==1 & !is.na(Day71bindSpike) & !is.na(Day71bindSpike_D614))
tmp$diff=tmp$Day71bindSpike - tmp$Day71bindSpike_D614
myboxplot(list(tmp$diff))
wilcox.test (tmp$Day71bindSpike, tmp$Day71bindSpike_D614, paired=T)
corplot(Day71bindSpike~Day71bindSpike_D614, tmp)
summary(10**tmp$diff)
```

Data integrity check
```{r}
dat.1=read.csv('/trials/covpn/p3003/analysis/correlates/Part_A_Blinded_Phase_Data/adata/janssen_partA_VL_data_processed_20240226.csv')
dat.2=read.csv('/trials/covpn/p3003/analysis/correlates/Part_A_Blinded_Phase_Data/adata/janssen_partA_VL_data_processed_20241015.csv')

tmp1=subset(dat.1, ph2.D29 & Trt==1 & Bserostatus==0 & Region==1)
mytable(!is.na(tmp1$Day71bindSpike), !is.na(tmp1$Day71bindSpike_D614), tmp1$EventIndPrimaryD29)
tmp2=subset(dat.2, ph2.D29 & Trt==1 & Bserostatus==0 & Region==1)
mytable(!is.na(tmp2$Day71bindSpike), !is.na(tmp2$Day71bindSpike_D614), tmp2$EventIndPrimaryD29)
identical(tmp1$Day71bindSpike, tmp2$Day71bindSpike)
identical(tmp1$Day29bindSpike, tmp2$Day29bindSpike)
```

## When is Delta wave in RSA?

```{r}
with(subset(dat_proc$EventTimePrimaryD29, Trt==1 & Region==2 & ph1.D29), table(seq1.variant.hotdeck1, EventIndPrimaryIncludeNotMolecConfirmedD1))

subset(dat_proc, Trt==1 & EventIndPrimaryIncludeNotMolecConfirmedD1==0 & Region==2 & seq1.variant.hotdeck1=="Delta", EventTimePrimaryD29)
```


## Others

```{r, echo=FALSE, include=FALSE}

################################################################################
# 

with(subset(dat_pooled_partA,ph1.D29==1), table(is.na(risk_score)))


with(subset(dat_proc, ph2.D29variant==1 & Region==1 & Trt==1), mytable(!is.na(Day29bindSpike), !is.na(Day29bindSpike_C.37_1)))


with(subset(dat_mapped, SubcohortIndPlus==1), mytable(!is.na(Day29bindSpike_D614), !is.na(Day71bindSpike_D614)))
with(subset(dat_mapped, SubcohortIndPlus==1), mytable(!is.na(Day29bindSpike_AY.1), !is.na(Day71bindSpike_AY.1)))

with(subset(dat_mapped, SubcohortIndPlus==1), mytable(!is.na(Day29bindSpike), !is.na(Day71bindSpike)))

with(subset(dat_mapped, SubcohortIndPlus==1), mytable(!is.na(Day71bindSpike), !is.na(Day71bindSpike_D614)))
with(subset(dat_mapped, SubcohortIndPlus==1), mytable(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614)))




################################################################################
# compare data before and after setting ID50 to NA for ARV

dat1=read.csv('/trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_PartAComplete_variant_mapped_20240123.csv')
dat2=read.csv('/trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_PartAComplete_variant_mapped_20240129.csv')

dim(dat2)
dim(dat1)
setdiff(names(dat2), names(dat1))
with(subset(dat2,Trt==1 & Bserostatus==0 & SubcohortInd), table(Region, ARVuseDay29))
with(subset(dat2,Trt==1 & Bserostatus==0 & EventIndPrimaryIncludeNotMolecConfirmedD29), table(Region, ARVuseDay29))



################################################################################
# missingness pattern


# bindRBD and bindSpike is all or none
table(!is.na(dat_mapped[,"Day29bindSpike"]), !is.na(dat_mapped[,"Day29bindRBD"]))

# the only difference bt Day29bindSpike and Day29pseudoneutid50 is that 4 ptids have Day29bindSpike but no Day29pseudoneutid50
# they are in the vaccine group and baseline neg and non-cases
with(subset(dat_proc, SubcohortInd==1), table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50), Bserostatus, Trt))
with(subset(dat_proc, SubcohortInd==1 | EventIndPrimaryIncludeNotMolecConfirmedD1==1), table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50), Bserostatus, Trt))

subset(dat_proc, SubcohortInd==1 & !is.na(Day29bindSpike) & is.na(Day29pseudoneutid50), c(Region, Bserostatus, Trt, EventIndPrimaryIncludeNotMolecConfirmedD1))


with(subset(dat_proc, SubcohortInd==1 & EventIndPrimaryIncludeNotMolecConfirmedD1==0 & Region==2), 
     table(!is.na(Day29bindSpike_D614), !is.na(Day29pseudoneutid50_Beta), Bserostatus, Trt))

with(subset(dat_proc, SubcohortInd==1 & EventIndPrimaryIncludeNotMolecConfirmedD1==0 & Region==1 ), 
     table(!is.na(Day29bindSpike_D614), (!is.na(Day29pseudoneutid50_Gamma) | !is.na(Day29pseudoneutid50_Lambda) | 
                                           !is.na(Day29pseudoneutid50_Mu) | !is.na(Day29pseudoneutid50_Zeta)), Bserostatus, Trt))

# do all cases have all variants Ab



dat=dat_mapped
table(!is.na(dat[dat$Region==0 & subc,"Day29bindSpike"]), !is.na(dat[dat$Region==0 & subc,"Day29pseudoneutid50"]), cases[dat$Region==0 & subc])

table(!is.na(dat[,"Day29bindSpike"]), !is.na(dat[,"Day29pseudoneutid50"]), cases, dat$Region)

with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0) , table(!is.na(Day29pseudoneutid50), !is.na(Day29bindSpike), SubcohortInd, forVariants))
with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0) , table(!is.na(Day29pseudoneutid50), !is.na(Day29bindSpike_D614), SubcohortInd, forVariants))


table(!is.na(dat_pooled_partA$Day29bindSpike), dat_pooled_partA$SubcohortInd, dat_pooled_partA$EventIndPrimaryD1)
table(!is.na(dat_mapped$Day29bindSpike), dat_mapped$SubcohortInd, dat_mapped$EventIndPrimaryIncludeNotMolecConfirmedD1)

table(!is.na(dat_pooled_partA$Day29pseudoneutid50), dat_pooled_partA$SubcohortInd, dat_pooled_partA$EventIndPrimaryD1)

with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29pseudoneutid50)), table(SubcohortInd, Region, forVariants))
with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29bindSpike_D614)), table(SubcohortInd, Region, forVariants))
with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29bindSpike)), table(SubcohortInd, Region, forVariants))

with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29bindSpike)), table(SubcohortInd, cc, forVariants))
with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29bindSpike_D614)), table(SubcohortInd, cc, forVariants))

with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29pseudoneutid50)), table(SubcohortInd, cc, forVariants))
with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29pseudoneutid50_Lambda)), table(SubcohortInd, cc, forVariants))


with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29pseudoneutid50_Lambda)), 
     table(SubcohortInd, cc, forVariants))

with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29bindSpike_D614)), 
     table(SubcohortInd, cc, forVariants))

with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29pseudoneutid50)), 
     table(SubcohortIndPlus, cc, forVariants))

with(subset(dat_mapped,EventIndPrimaryIncludeNotMolecConfirmedD1==0 & !is.na(Day29bindSpike)), 
     table(SubcohortIndPlus, cc, forVariants))






# are there any cases with variant Ab data but not D614/D614G Ab data?  
table(!is.na(dat_mapped[,"Day29bindSpike_D614"]), !is.na(dat_mapped[,"Day29bindSpike"]), subc)
table(!is.na(dat_mapped[,"Day29bindSpike_D614"]), !is.na(dat_mapped[,"Day29bindSpike"]), cases)
table(!is.na(dat_mapped[kp & subc,"Day29bindSpike_D614"]), !is.na(dat_mapped[kp & subc,"Day29bindSpike"]))

table(!is.na(dat_mapped[,"Day29pseudoneutid50_Lambda"]), !is.na(dat_mapped[,"Day29pseudoneutid50"]), subc)
table(!is.na(dat_mapped[,"Day29pseudoneutid50_Lambda"]), !is.na(dat_mapped[,"Day29pseudoneutid50"]), cases)
table(!is.na(dat_mapped[kp & subc,"Day29pseudoneutid50_Lambda"]), !is.na(dat_mapped[kp & subc,"Day29pseudoneutid50"]))


# variants are measured on the same set of ptids within region of interest
table(!is.na(dat_mapped[,"Day29pseudoneutid50_Lambda"])[kp & dat_mapped$Region==1], !is.na(dat_mapped[,"Day29bindSpike_D614"])[kp & dat_mapped$Region==1])
table(!is.na(dat_mapped[,"Day29pseudoneutid50_Beta"])[kp & dat_mapped$Region==2], !is.na(dat_mapped[,"Day29bindSpike_D614"])[kp & dat_mapped$Region==2])

with(dat_mapped[kp & dat_mapped$Region==1 & !is.na(dat_mapped$Day29pseudoneutid50_Lambda),], table(SubcohortInd,cc))

with(dat_mapped[kp & dat_mapped$Region==2 & !is.na(dat_mapped$Day29pseudoneutid50_Beta),], table(SubcohortInd,cc))



# in the subcohort, bindSpike and ID50 D614G are mostly all or none, spike has just 4 more
# but there are many more id50 outside subcohort
table(!is.na(dat_mapped[,"Day29bindSpike"]), !is.na(dat_mapped[,"Day29pseudoneutid50"]))
table(!is.na(dat_mapped[kp,"Day29bindSpike"]), !is.na(dat_mapped[kp,"Day29pseudoneutid50"]))
table(!is.na(dat_mapped[kp & SubcohortInd,"Day29bindSpike"]), !is.na(dat_mapped[kp & SubcohortInd,"Day29pseudoneutid50"]))


table(!is.na(dat_mapped[,"Day29pseudoneutid50_Lambda"]), !is.na(dat_mapped[,"Day29pseudoneutid50"]))
table(!is.na(dat_mapped[kp,"Day29pseudoneutid50_Lambda"]), !is.na(dat_mapped[kp,"Day29pseudoneutid50"]))
table(!is.na(dat_mapped[kp & dat_mapped$SubcohortInd,"Day29pseudoneutid50_Lambda"]), !is.na(dat_mapped[kp & dat_mapped$SubcohortInd,"Day29pseudoneutid50"]))


with(dat_mapped[select & dat_mapped$Region==0, ], table(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614)))
with(dat_mapped[select & dat_mapped$Region==2, ], table(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614)))
with(dat_mapped[select & dat_mapped$Region==1, ], table(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614)))




with(dat_mapped[select & dat_mapped$Region==0, ], table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50)))
with(dat_mapped[select & dat_mapped$Region==2, ], table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50_Beta)))
with(dat_mapped[select & dat_mapped$Region==1, ], table(!is.na(Day29bindSpike), (!is.na(Day29pseudoneutid50_Gamma) | !is.na(Day29pseudoneutid50_Lambda) | !is.na(Day29pseudoneutid50_Mu) | !is.na(Day29pseudoneutid50_Zeta))))

with(dat_mapped[select & dat_mapped$Region==1, ], table(!is.na(Day29pseudoneutid50_Gamma), !is.na(Day29pseudoneutid50_Lambda), !is.na(Day29pseudoneutid50_Mu), !is.na(Day29pseudoneutid50_Zeta)))

with(dat_mapped[select & dat_mapped$Region==1, ], table(!is.na(Day29pseudoneutid50_Gamma), !is.na(Day29pseudoneutid50_Zeta)))
with(dat_mapped[select & dat_mapped$Region==1, ], table(!is.na(Day29pseudoneutid50_Lambda), !is.na(Day29pseudoneutid50_Zeta)))
with(dat_mapped[select & dat_mapped$Region==1, ], table(!is.na(Day29pseudoneutid50_Mu), !is.na(Day29pseudoneutid50_Zeta)))

# no delta in region 1, but there is in 0 and 2


with(dat_mapped, table(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614), Region))
with(dat_mapped[dat_mapped$SubcohortInd==1,], table(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614), Region))

with(dat_mapped,                              table(!is.na(Day29pseudoneutid50), !is.na(Day29pseudoneutid50_Beta), Region))
with(dat_mapped[dat_mapped$SubcohortInd==1,], table(!is.na(Day29pseudoneutid50), !is.na(Day29pseudoneutid50_Beta), Region))


with(dat_mapped[kp,], table(!is.na(Day29pseudoneutid50), !is.na(Day29pseudoneutid50_Beta), Region))
with(dat_mapped[select ,], table(!is.na(Day29pseudoneutid50), !is.na(Day29pseudoneutid50_Beta), Region))


with(dat_mapped[kp,], table(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614), Region))
with(dat_mapped[select ,], table(!is.na(Day29bindSpike), !is.na(Day29bindSpike_D614), Region))


# distribution of variant bAb in controls by Region and subcohort
with(dat_mapped[kp & !is.na(dat_mapped$Day29bindSpike_D614),], table(Region, SubcohortInd))
with(dat_mapped, table(Region, SubcohortInd))

# distribution of variant bAb in cases by Region and subcohort
with(dat_mapped[!kp & !is.na(dat_mapped$Day29bindSpike), ,], table(Region, !is.na(Day29bindSpike_D614)))
with(dat_mapped[!kp , ], table(Region, !is.na(Day29bindSpike_D614)))


# distribution of Beta ID50 in controls by Region and subcohort
with(dat_mapped[kp & !is.na(dat_mapped$Day29pseudoneutid50_Beta),], table(Region, SubcohortInd))
# distribution of variant nAb in cases by Region and subcohort
with(dat_mapped[!kp & !is.na(dat_mapped$Day29pseudoneutid50), ,], table(Region, !is.na(Day29pseudoneutid50_Beta)))
with(dat_mapped[!kp , ], table(Region, !is.na(Day29pseudoneutid50_Beta)))


# distribution of Lambda ID50 in controls by Region and subcohort
with(dat_mapped[kp & !is.na(dat_mapped$Day29pseudoneutid50_Lambda),], table(Region, SubcohortInd))
# distribution of variant nAb in cases by Region and subcohort
with(dat_mapped[!kp & !is.na(dat_mapped$Day29pseudoneutid50), ,], table(Region, !is.na(Day29pseudoneutid50_Lambda)))
with(dat_mapped[!kp , ], table(Region, !is.na(Day29pseudoneutid50_Lambda)))



# RSA
# non-cases
# everyone who has Beta also has ancestral
with(subset(dat_proc,Trt==1 & ph1.D29 & Region==2 & !EventIndPrimaryHasVLD29), table(!is.na(Day29pseudoneutid50), !is.na(Day29pseudoneutid50_Beta)))

# LatAm
# non-cases
# everyone who has Gamma also has ancestral
with(subset(dat_proc,Trt==1 & ph1.D29 & Region==1 & !EventIndPrimaryHasVLD29), table(!is.na(Day29pseudoneutid50), !is.na(Day29pseudoneutid50_Gamma)))
# same set of ptids have Gamma etc
with(subset(dat_proc,Trt==1 & ph1.D29 & Region==1 & !EventIndPrimaryHasVLD29), table(!is.na(Day29pseudoneutid50_Gamma), !is.na(Day29pseudoneutid50_Mu)))
with(subset(dat_proc,Trt==1 & ph1.D29 & Region==1 & !EventIndPrimaryHasVLD29), table(!is.na(Day29pseudoneutid50_Gamma), !is.na(Day29pseudoneutid50_Zeta)))
with(subset(dat_proc,Trt==1 & ph1.D29 & Region==1 & !EventIndPrimaryHasVLD29), table(!is.na(Day29pseudoneutid50_Gamma), !is.na(Day29pseudoneutid50_Lambda)))
# cases
with(subset(dat_proc,Trt==1 & ph1.D29 & Region==1), table(!is.na(Day29pseudoneutid50_Gamma), !is.na(Day29pseudoneutid50_Mu), EventIndPrimaryHasVLD29, useNA="ifany"))



################################################################################
# correlation between two ancestral ID50 markers

corplot(Day29bindSpike~Day29bindSpike_D614, dat_mapped)

corplot(Day29bindSpike~Day29bindSpike_D614, dat_mapped[dat_mapped$Day29bindSpike>1,])

mytable(!is.na(dat_mapped$Day29bindSpike), !is.na(dat_mapped$Day29bindSpike_D614))
mytable(!is.na(dat_mapped$Day29pseudoneutid50), !is.na(dat_mapped$Day29pseudoneutid50_Lambda))

dat=dat_mapped[,"Day29"%.%assays[c(1,4:13)]]
names(dat)=sub("Day29bindSpike","",names(dat))
mypairs(dat)


with(subset(dat_mapped, SubcohortInd==1), table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50)))
with(subset(dat_mapped, EventIndPrimaryIncludeNotMolecConfirmedD1==1), table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50)))
with(subset(dat_mapped, SubcohortInd==1), table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50), Region))
with(subset(dat_mapped, EventIndPrimaryIncludeNotMolecConfirmedD1==1), table(!is.na(Day29bindSpike), !is.na(Day29pseudoneutid50), Region))


```