---
title: "Covail Modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(copcor)
library(survey)
library(kyotil)
library(glue)
library(Hmisc)
library(knitr)

dat_proc=read.csv('/trials/covpn/COVAILcorrelates/analysis/correlates/adata/covail_data_processed_20250508.csv')
dat_mapped=read.csv('/trials/covpn/COVAILcorrelates/analysis/mapping_immune_correlates/adata/covail_mapped_data_20250424.csv')
dat=subset(dat_proc, ph1.D15 & TrtonedosemRNA==1) 

assay_metadata=read.csv('~/correlates_reporting2/assay_metadata/covail_assay_metadata.csv')
assays=assay_metadata$assay
tmp=assay_metadata$assay[8:nrow(assay_metadata)]
S1=tmp[!endsWith(tmp, ".N")]%.%"1"; S1
S2=tmp[!endsWith(tmp, ".N")]%.%"2"; S2
N=tmp[endsWith(tmp, "Wuhan.N")]; N
tcellvv=c(S1, S2, N)

f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ FOIstandardized + standardized_risk_score

primary = c("Bcd4_IFNg.IL2_Wuhan.N", "Bcd4_IFNg.IL2_BA.4.5.S", "Day15cd4_IFNg.IL2_BA.4.5.S")
nAbs=subset(assay_metadata, panel=="id50", assay, drop=T)

# compare all Pfizer and all Moderna and onedosemRNA to decide whether to stratify by stage or not
dat.onedosemRNA =    subset(dat_proc, ph1.D15 & TrtonedosemRNA==1 & !arm %in% c(16,17)) 
dat.onedoseModerna = subset(dat.onedosemRNA, arm<=6)
dat.onedosePfizer  = subset(dat.onedosemRNA, arm> 6)

```

## Intro

The antibody data includes arm 16 and 17. The T cell data excludes arm 16 and 17.

```{r compare ph1 between antibody study and t cell study}
mytable(dat_proc$ph1.D15, dat_proc$ph1.D15.tcell)
mytable(dat_proc$ph1.D15, dat_proc$arm)
mytable(dat_proc$ph1.D15.tcell, dat_proc$arm)
mytable(dat.onedosemRNA$ph1.D15.tcell, dat.onedosemRNA$ph1.D15)

```



### Exploratory

```{r, fig.width=8, fig.height=8}
mypairs(dat_proc[,c("Bcd4_IFNg.IL2_Wuhan.N", "Bcd4_IFNg.IL2_BA.4.5.S", "Day15cd4_IFNg.IL2_BA.4.5.S", "Bpseudoneutid50_D614G", "Day15pseudoneutid50_D614G", "Bpseudoneutid50_BA.4.BA.5", "Day15pseudoneutid50_BA.4.BA.5")])
mypairs(dat_proc[,c("Bcd4_IFNg.IL2_Wuhan.N", "Bcd4_IFNg.IL2_BA.4.5.S", "Day15cd4_IFNg.IL2_BA.4.5.S")])
```

## Multivariate models

```{r }
design=  twophase(id = list( ~ 1,  ~ 1), strata = list(NULL,  ~ Wstratum), subset =  ~ ph2.D15.tcell, data = subset(dat.onedosemRNA, naive==0))

fits=list(
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Bcd4_IFNg.IL2_BA.4.5.S + Day15cd4_IFNg.IL2_BA.4.5.S + Bpseudoneutid50_BA.4.BA.5 + Day15pseudoneutid50_BA.4.BA.5, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Bcd4_IFNg.IL2_BA.4.5.S  + Day15pseudoneutid50_BA.4.BA.5, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Bcd4_IFNg.IL2_BA.4.5.S + Day15cd4_IFNg.IL2_BA.4.5.S, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Bpseudoneutid50_BA.4.BA.5 + Day15pseudoneutid50_BA.4.BA.5, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Bpseudoneutid50_BA.4.BA.5 + Bcd4_IFNg.IL2_BA.4.5.S, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Day15cd4_IFNg.IL2_BA.4.5.S + Day15pseudoneutid50_BA.4.BA.5, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Day15cd4_IFNg.IL2_BA.4.5.S + Bpseudoneutid50_BA.4.BA.5, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Bcd4_IFNg.IL2_BA.4.5.S + Day15pseudoneutid50_BA.4.BA.5 + Bcd4_IFNg.IL2_Wuhan.N, design)
,
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ Bcd4_IFNg.IL2_BA.4.5.S + Bcd4_IFNg.IL2_Wuhan.N, design)
)
tab=getFormattedSummary(fits, robust=T, exp=T, type=5); 
tab[is.na(tab)]=""
kable(tab)

fits=list(
  svycoxph(f=Surv(COVIDtimeD22toD181, COVIDIndD22toD181) ~ I(scale(Bcd4_IFNg.IL2_BA.4.5.S)) * I(scale(Day15pseudoneutid50_BA.4.BA.5)), design)
)
tab=getFormattedSummary(fits, robust=T, exp=T, type=5); 
tab[is.na(tab)]=""
kable(tab)
```



```{r }
summary(dat_proc$Bcd4_IL4.IL5.IL13.154_BA.4.5.S)

dat.onedosemRNA$Bcd4_IL4.IL5.IL13.154_BA.4.5.S_alt = pmax(-1.699, dat.onedosemRNA$Bcd4_IL4.IL5.IL13.154_BA.4.5.S)
dat.onedosemRNA$Day15cd4_IL4.IL5.IL13.154_BA.4.5.S_alt = pmax(-1.699, dat.onedosemRNA$Day15cd4_IL4.IL5.IL13.154_BA.4.5.S)

design=  twophase(id = list( ~ 1,  ~ 1), strata = list(NULL,  ~ Wstratum), subset =  ~ ph2.D15.tcell, data = subset(dat.onedosemRNA, naive==0))

fit = svycoxph(f=Surv(COVIDtimeD22toD91, COVIDIndD22toD91) ~ Bcd4_IL4.IL5.IL13.154_BA.4.5.S, design)
summary(fit)

fit = svycoxph(f=Surv(COVIDtimeD22toD91, COVIDIndD22toD91) ~ Bcd4_IL4.IL5.IL13.154_BA.4.5.S_alt, design)
summary(fit)

fit = svycoxph(f=Surv(COVIDtimeD22toD91, COVIDIndD22toD91) ~ Day15cd4_IL4.IL5.IL13.154_BA.4.5.S_alt, design)
summary(fit)


myboxplot(Bcd4_IL4.IL5.IL13.154_BA.4.5.S_alt~COVIDIndD22toD91, subset(dat.onedosemRNA, naive==0), names=c("non-cases", "cases"))
mytable(subset(dat.onedosemRNA, naive==0, Bcd4_IL4.IL5.IL13.154_BA.4.5.S_alt))
mytable(subset(dat.onedosemRNA, naive==0, Day15cd4_IL4.IL5.IL13.154_BA.4.5.S_alt))
```