---
title: "IB-201P and IB-202P Exploratory Plots (I)"
output: 
  pdf_document:
    includes:
      in_header: preamble.tex
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

library(copcor)
library(survey)
library(kyotil)
library(glue)
library(Hmisc)
library(knitr)
library(GGally)
library(saws)

library(geepack)
source("~/correlates_reporting2/cor_poisson/code/gee_bias_correction.R")


dat_mapped_202=read.csv(config::get(config = "iliad_ib202p", file="/home/yfong/correlates_processing/config.yml")$mapped_data)
dat_proc_202=read.csv(config::get(config = "iliad_ib202p", file="/home/yfong/correlates_reporting2/config.yml")$data_cleaned)
dat_proc_202$Ptid = as.factor(dat_proc_202$Ptid) # need to make it a factor to use as id

dat_mapped_201=read.csv(config::get(config = "iliad_ib201p", file="/home/yfong/correlates_processing/config.yml")$mapped_data)
dat_proc_201=read.csv(config::get(config = "iliad_ib201p", file="/home/yfong/correlates_reporting2/config.yml")$data_cleaned)

assay_metadata=read.csv(glue('~/correlates_reporting2/assay_metadata/iliad_ib202p_assay_metadata.csv'))
assays = assay_metadata$assay
panels = unique(assay_metadata$panel)
antigens = c("WCE", setdiff(unique(assay_metadata$antigen), c("WCE", NA)))
```


```{r covariates selection, echo=F}

fit1 = glm(EventIndC9_11_14 ~ Sex, subset(dat_proc_202, Trt=="BPZE1"), family=poisson(link = "log"))
fit2 = glm(EventIndC9_11_14 ~ Age, subset(dat_proc_202, Trt=="BPZE1"), family=poisson(link = "log"))
tab=getFormattedSummary(list(Sex=fit1, Age=fit2), robust=T, exp=T)[2,,drop=F]
rownames(tab)[1]=""
kable(tab, align="c")
```

```{r geepack, echo=F}

fit.gee <- geeglm(EventIndC9_11_14 ~ Day28WCE_Norm_Nasal_IgA, data  = subset(dat_proc_202, Trt == "BPZE1"), family= poisson(link = "log"),
  id = Ptid, corstr= "independence")

summary(fit.gee)   # robust (sandwich) SEs by default

ssase (fit.gee)

```

```{r spot check wilcox robust binomial}
dat= subset(dat_proc_202, Trt=="PBO")

myboxplot(Delta28overBFHA_Norm_Nasal_IgA~EventIndC9_11_14, dat, test="w")

fit = glm(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"))
getFormattedSummary(list(fit), robust=T)
getFormattedSummary(list(fit), robust=F)

fit = glm(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=binomial(link = "logit"))
getFormattedSummary(list(fit), robust=T)
getFormattedSummary(list(fit), robust=F)


myboxplot(BFHA_Norm_Nasal_IgA~EventIndC9_11_14, dat, test="w")

fit = glm(EventIndC9_11_14 ~ BFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"))
getFormattedSummary(list(fit), robust=T, type=2)
getFormattedSummary(list(fit), robust=F, type=2)

fit = geeglm(EventIndC9_11_14 ~ BFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")
ssase (fit)
getFormattedSummary(list(fit), robust=T, type=2)


fit = glm(EventIndC9_11_14 ~ BFHA_Norm_Nasal_IgA, dat, family=binomial(link = "logit"))
getFormattedSummary(list(fit), robust=T)
getFormattedSummary(list(fit), robust=F)

getFormattedSummary(list(mgee(EventIndC9_11_14 ~ BFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")), robust=T, finite="dm", type=2)



getFormattedSummary(list(mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")), robust="d5", type=2)

getFormattedSummary(list(mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")), robust="d4", type=2)

getFormattedSummary(list(mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")), robust="d3", type=2)

getFormattedSummary(list(mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")), robust="d2", type=2)

getFormattedSummary(list(mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")), robust=T, type=2)

getFormattedSummary(list(mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")), robust=F, type=2)

getFormattedSummary(list(glm(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"))), robust=T, type=2)


fit.mgee = mgee(EventIndC9_11_14 ~ BFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")

saws(fit.mgee,method="dm")$se
saws(fit.mgee,method=c("d1"),bound=.75)$se
saws(fit.mgee,method=c("d2"),bound=.75)$se
saws(fit.mgee,method=c("d3"),bound=.75)$se
saws(fit.mgee,method=c("d4"),bound=.75)$se
saws(fit.mgee,method=c("d5"),bound=.75)$se


fit.mgee = mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson(link = "log"), id = Ptid, corstr= "independence")
# saws(fit.mgee,method="dm")$se # model-based
saws(fit.mgee,method=c("d1"),bound=.75)$se
saws(fit.mgee,method=c("d2"),bound=.75)$se
saws(fit.mgee,method=c("d3"),bound=.75)$se
saws(fit.mgee,method=c("d4"),bound=.75)$se
saws(fit.mgee,method=c("d5"),bound=.75)$se


fit.mgee = mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=gaussian, id = Ptid, corstr= "independence")
# saws(fit.mgee,method="dm")$se # model-based
saws(fit.mgee,method=c("d1"),bound=.75)$se
saws(fit.mgee,method=c("d2"),bound=.75)$se
saws(fit.mgee,method=c("d3"),bound=.75)$se
saws(fit.mgee,method=c("d4"),bound=.75)$se
saws(fit.mgee,method=c("d5"),bound=.75)$se

fit =    geeglm(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=gaussian, id = Ptid, corstr= "independence")
mysapply(ssase (fit), function (v) sqrt(diag(v)))


```



```{r test gee_bias_correction_for_poisson}

fit.mgee = mgee(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson, id = Ptid, corstr= "independence")

# saws(fit.mgee,method="dm")$se # model based
saws(fit.mgee,method=c("d1"),bound=.75)$se
saws(fit.mgee,method=c("d2"),bound=.75)$se
saws(fit.mgee,method=c("d3"),bound=.75)$se
saws(fit.mgee,method=c("d4"),bound=.75)$se
saws(fit.mgee,method=c("d5"),bound=.75)$se

fit =    geeglm(EventIndC9_11_14 ~ Delta28overBFHA_Norm_Nasal_IgA, dat, family=poisson, id = Ptid, corstr= "independence")
mysapply(ssase (fit), function (v) sqrt(diag(v)))


```