---
output:
  pdf_document: default
  html_document: default
---
#  Graphical Descriptions of Antibody Marker Data {#ab-grapical}

```{r, echo=FALSE, message=FALSE}
message("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ running cor_graphical report ~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
```


```{r, echo=FALSE, results='asis'}
library(here)
library(knitr)
library(latex2exp)
here::i_am("cor_graphical/report.Rmd")


if (!(study_name %in% c("ENSEMBLE", "MockENSEMBLE", "janssen_partA_VL", "IARCHPV", "VAT08", "UK302", "COVAIL")) & !grepl("stage2|prevent19nvx", attr(config,"config"))) {
  plot_ve_curves <- readRDS(here::here("cor_graphical", "data_clean", "plot_ve_curves.rds"))
}

# called in report_violin etc
bsero <- ifelse(study_name=="IARCHPV", "", "BaselineNeg")
bseroLabel <- ifelse(bsero=="BaselinePos", "baseline positive", 
                     ifelse(bsero=="BaselineNeg", "baseline negative", ""))

# temporary setting due to unknown reason for assays including bAb for id27hpvnAb
if (attr(config,"config")=="id27hpvnAb") {assays = assays[!grepl("bind", assays)]}
if (attr(config,"config") %in% c("prevent19_stage2","prevent19nvx")) {
  times = c("Day35")
  time_labels = c("Day 35")
}
if (attr(config,"config")=="azd1222_stage2") {
  times = c("Day57","Day90","Day180","Day360")
  time_labels = c("Day 57", "Day 90","Day 180","Day 360")
}

tps_no_delta_over_tinterm <-  times[!times %in% c(paste0("Delta",timepoints[length(timepoints)],"over",timepoints[1]))] #c("B", "Day29", "Delta29overB", "Day57", "Delta57overB")
tps_no_delta_over_tinterm_lb <- if(attr(config,"config")=="vat08_combined") {c("Day 1_nn", "Day 22_nn", "Day 43_nn", "D22 fold-rise over D1_nn", "D43 fold-rise over D1_nn")
  } else {time_labels[! grepl(paste0("over D",timepoints[1]),  time_labels)]}
tps_no_fold_change <- times[!grepl("Delta", times)]
tps_no_B_and_fold_change <- times[!grepl("Delta", times) & times!="B"]

#if(file.exists(here::here('cor_graphical', paste0('report_', tolower(study_name), '.Rmd')))) {
  
#  message ("trial-specific report rmd found")
#  res = knitr::knit_child(c(here::here('cor_graphical', paste0('report_', tolower(study_name), '.Rmd'))), quiet = TRUE)
#  cat(res, sep = '\n')

#} else {
  #### COR folder postfix
  # for Sanofi, needs to loop through "", "omi"
  # for ENSEMBLE EUA, loop through "IncludeNotMolecConfirmed", "IncludeNotMolecConfirmedstart1"
  # for ENSEMBLE part A ancestral strain, loop through "SevereIncludeNotMolecConfirmed" or "ModerateIncludeNotMolecConfirmed" as needed
  # for ENSEMBLE part A variant, no loop, present adhoc figures
  # for other studies, loop through ""
  COR_postfix_list = ""
  if (study_name=="ENSEMBLE" & grepl("EUA", attr(config,"config"))) COR_postfix_list <- c("IncludeNotMolecConfirmed", "IncludeNotMolecConfirmedstart1")
  if (study_name=="ENSEMBLE" & grepl("partA$", attr(config,"config"))) COR_postfix_list <- c("IncludeNotMolecConfirmed") # ModerateIncludeNotMolecConfirmed SevereIncludeNotMolecConfirmed
  if (study_name=="ENSEMBLE" & attr(config,"config") == "janssen_partA_VL") COR_postfix_list <- c("adhoc")
  if (study_name=="IARCHPV") COR_postfix_list <- c("", "sus")
  if (attr(config,"config")=="prevent19_stage2") COR_postfix_list <- c("delta", "severe")
  if (attr(config,"config")=="azd1222_stage2") COR_postfix_list <- c("delta nab", "delta bab",
                                                                     "severe nab", "severe bab"
                                                                     )
  if (attr(config,"config") == "nvx_uk302") COR_postfix_list <- c("D35nvx_uk302")
  if (attr(config,"config") == "prevent19nvx") COR_postfix_list <- c("D35prevent19nvx")
  if (study_name=="VAT08") COR_postfix_list <- c("D22D43omi_stage1")

  if (COR_postfix_list == "adhoc"){ # only for config: janssen_partA_VL and COR: D29VLvariant
    
    COR = "D29VLvariant"
    COR_postfix_label=""
    
    tp="Day29"
    tp_lb="Day 29"
    trt_lb=": Vaccine Arm."
    trt="vaccine_bseroneg"
    
    #for (region in c("LA", "SA")) {
    #  for (marker in ("NAb" #,"Spike", "NAb_Spike"
    #                  )) {
    #              marker_lb = ifelse(marker=="NAb", "PsV-nAb ID50 Markers", ifelse(marker=="Spike", "Anti-Spike Binding Ab Markers", ifelse(marker=="NAb_Spike", "PsV-nAb ID50 and Anti-Spike Binding Ab Markers")))
                  
    #              pair_title_beginner = "Pairwise Correlation Matrix between "
    #    		      res = knitr::knit_child(c(here::here('cor_graphical', 'report_pair_variant.Rmd')), quiet = TRUE)
    #    		      cat(res, sep = '\n')
    #    		      cat("\\clearpage", sep = '\n')
        		      
    #  }
    #}
    
    for (region in c("LATAM", #"LATAM_pooled", 
                     "ZA"#, #"ZA_pooled"
                     )) {

    }
    
    
    for (region in c("LATAM", "ZA")) {

    }
    
    for (region in c("LATAM", "ZA", "NAM")) {

    }
    
  } else if (study_name == "VAT08" | attr(config,"config") %in% c("prevent19_stage2","azd1222_stage2","nvx_uk302","prevent19nvx")){
    
    for (COR_postfix in COR_postfix_list){
        
      # show in figure title
      COR_postfix_label = ""
      if (grepl("delta", COR_postfix)) COR_postfix_label=" (Delta Endpoint)"
      if (grepl("severe", COR_postfix)) COR_postfix_label=" (Severe Endpoint)"
      if (COR_postfix=="D22D43omi_stage1") COR_postfix_label= paste0(" (Stage1)")
      if (COR_postfix=="D22D43omi_stage2") COR_postfix_label= paste0(" (Stage2)")
      
      COR=case_when(COR_postfix=="" ~ "", 
                    COR_postfix=="delta" ~ "D35prevent19_stage2_delta", 
                    COR_postfix=="severe" ~ "D35prevent19_stage2_severe",
                    COR_postfix=="delta nab" ~ "D57azd1222_stage2_delta_nAb", 
                    COR_postfix=="delta bab" ~ "D57azd1222_stage2_delta_bAb", 
                    COR_postfix=="severe nab" ~ "D57azd1222_stage2_severe_nAb", 
                    COR_postfix=="severe bab" ~ "D57azd1222_stage2_severe_bAb",
                    !is.na(COR_postfix) ~ COR_postfix
                    )
      
      # SET 1
      for (a in c("pseudoneutid50", if(attr(config,"config")!="prevent19_stage2") "bindSpike", if(attr(config,"config") %in% c("prevent19_stage2","azd1222_stage2")) "bindSpike_sub_stage2")){
             
        if ((grepl("nab", COR_postfix) & !grepl("pseudoneutid50", a)) | (grepl("bab", COR_postfix) & !grepl("bindSpike", a))) next # for AZ stage 2
        if (a == "pseudoneutid50" & attr(config,"config") %in% c("nvx_uk302","prevent19nvx")) next # no id50 for nvx_uk302, prevent19nvx
    
        for (tp in tps_no_delta_over_tinterm_lb){
          
          if(attr(config,"config")=="azd1222_stage2" & tp=="Day 360") next # do not have this for azd1222_stage2
          
          tpLabel = gsub("_n", " naive", gsub("_nn", " non naive", tolower(tp)))
          aLabel = gsub("_sub_stage2", " subset", a)
          res = knitr::knit_child(c(here::here('cor_graphical', 'report_set1.Rmd')), quiet = TRUE)
          cat(res, sep = '\n')
          cat("\\clearpage", sep = '\n')
        }
      }
      
      if (attr(config,"config") == "nvx_uk302") next # break the loop for nvx_uk302
      
      # SET 2
      assay_grp_list = if(attr(config,"config")=="vat08_combined"){
        c(paste0(assays[!assays=="bindSpike_mdw"][1:2], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][3:4], collapse="_"), 
                          paste0(assays[!assays=="bindSpike_mdw"][5:6], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][7:8], collapse="_"),
                          "bindSpike_mdw",
                          paste0(assays[!assays=="bindSpike_mdw"][9:10], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][11:12], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][13:14], collapse="_")
        )} else if (attr(config,"config")=="prevent19_stage2"){
          c("pseudoneutid50_D614G_pseudoneutid50_Delta","bindSpike_D614_bindSpike_Delta1")
        } else if (grepl("bab", COR_postfix)){ # for azd1222_stage2
          assays[grepl("bindSpike", assays)]
        } else if (grepl("nab", COR_postfix)){ # for azd1222_stage2
          assays[grepl("pseudoneutid50", assays)]
        } else {assays}
      

      
      # SET 3
      if (COR=="D57azd1222_stage2_delta_bAb") {
        # adhoc figure
      }
      
      for (bsero in c("non_naive")){
        if (attr(config,"config") %in% c("prevent19_stage2","azd1222_stage2","prevent19nvx")) next # prevent19_stage2, azd1222_stage2, prevent19nvx don't have non_naive
        
          for (trt in c("vac_pla")){
              
              for (tp in if(attr(config,"config")=="vat08_combined") {tps_no_delta_over_tinterm} else {tps_no_fold_change}){
                
                for (assay_n in c(length(assays), 
                                  if (attr(config,"config") == "vat08_combined") 9, 
                                  if (attr(config,"config") == "vat08_combined") 6,
                                  if (attr(config,"config") == "vat08_combined") 10, 
                                  if (attr(config,"config") == "vat08_combined") 7)){
                  
                }
              }
          }
      }
      
      for (bsero in c("naive")){
          
          for (trt in c("vac")){
              
              for (tp in if (attr(config,"config")=="prevent19_stage2") {c("Day35","Day35_sub")
                } else if (attr(config,"config")=="vat08_combined") {tps_no_delta_over_tinterm[2:5]
                  } else {tps_no_B_and_fold_change}){
                  
                  
                  assay_n = ifelse(COR %in% c("D57azd1222_stage2_delta_nAb", "D57azd1222_stage2_severe_nAb"), sum(grepl("pseudoneutid50", assays)),
                                   ifelse(COR %in% c("D57azd1222_stage2_delta_bAb", "D57azd1222_stage2_severe_bAb"), sum(grepl("bindSpike", assays)),
                                      length(assays)))
                  if (tp == "Day35_sub"){assay_n = 4; tp = "Day35" 
                  # hard code to pool a subset pair plot for prevent19_stage2 
                  } else {assay_n = length(assays)}  
                  
                  for (assay_n in c(assay_n, 
                                  if (attr(config,"config") == "vat08_combined") 9, 
                                  if (attr(config,"config") == "vat08_combined") 6,
                                  if (attr(config,"config") == "vat08_combined") 10, 
                                  if (attr(config,"config") == "vat08_combined") 7)) {
                  
                  }
              }
          }
      }
      
      if (attr(config,"config") == "prevent19nvx") next # break the loop for prevent19nvx
      
      # SET 4
      for (a in assays){
          
          
      }
      
      # adhoc for vat08
      if (attr(config,"config") == "vat08_combined" & COR_postfix_list == "D22D43omi_stage1"){
        
      }
  }
    
    

  } else if (study_name=="COVAIL"){
  
  assay_metadata <- assay_metadata %>% filter(panel=="id50")
  assays <- assay_metadata$assay

  set1_panels_1 = c("id50")
  set1_group_1= c(" (13 one-dose mRNA booster arms pooled)",
                  " (13 one-dose mRNA booster arms pooled: naive vs. non-naive)",
                  " (3 Sanofi booster arms pooled)",
                  " (mRNA Moderna vs. mRNA Pfizer)",
                  " (mRNA Prototype vs. mRNA Omicron-Containing)",
                  " (Moderna: mRNA Prototype vs. mRNA Omicron-Containing)",
                  " (Pfizer: mRNA Prototype vs. mRNA Omicron-Containing)",
                  " (mRNA Bivalent vs. mRNA Monovalent)")
  set1_group_2= c(" (13 one-dose mRNA booster arms pooled)", " (3 Sanofi booster arms pooled)")

  set1_times <- c("B","Day15","Delta15overB")
  
  set2_times = c("B","Day15","Day29","Day91")
  
  
  ## Set 1: violin and line plots #############
  for (strain in c("6_strain")){
    for (panel in set1_panels_1){
      for (group in set1_group_1){
        for (time in set1_times) {
        
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
        }
      }
    }
    }

## Set 3: Correlation plots across markers at a given time point #############

## Set 4: Correlation plots for a given marker across time points #############


} else { # for all other studies but config: janssen_partA_VL and COR: D29variant
  
    for (COR_postfix in COR_postfix_list){
        
      # show in figure title
      COR_postfix_label = ""
      if (COR_postfix == "IncludeNotMolecConfirmedstart1") COR_postfix_label=" (start1)"
      if (COR_postfix == "ModerateIncludeNotMolecConfirmed") COR_postfix_label=" (Moderate Endpoint)"
      if (COR_postfix == "SevereIncludeNotMolecConfirmed") COR_postfix_label=" (Severe Endpoint)"
      if (COR_postfix == "omi") COR_postfix_label=" (Omicron Endpoint)"
      if (COR_postfix == "sus") COR_postfix_label=" (sus)"
  
      
    }
  }

  #}
#}
  



```
