---
output:
  pdf_document: default
  html_document: default
---
#  Graphical Descriptions of Antibody Marker Data {#ab-grapical}
\clearpage
```{r, echo=FALSE, message=FALSE}
message("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ running cor_graphical report ~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
```


```{r, echo=FALSE, results='asis'}
library(here)
library(knitr)
library(latex2exp)
here::i_am("cor_graphical/report.Rmd")


if (!(study_name %in% c("ENSEMBLE", "MockENSEMBLE", "janssen_partA_VL", "IARCHPV", "VAT08", "UK302", "COVAIL", "VaxArt_Mock", "ILIAD_IB202P")) & !grepl("stage2|prevent19nvx", attr(config,"config"))) {
  plot_ve_curves <- readRDS(here::here("cor_graphical", "data_clean", "plot_ve_curves.rds"))
}
if (study_name=="VAT08") {
  dat.longer.cor.subset.plot1 <- readRDS(here::here("cor_graphical", "data_clean", "longer_cor_data_plot1.rds"))
  Trialstage_val = unique(dat.longer.cor.subset.plot1$Trialstage)
} else {Trialstage_val = 999} # not applicable to other studies

# called in report_violin etc
bsero <- ifelse(study_name %in% c("IARCHPV", "ILIAD_IB202P"), "", "BaselineNeg")
bseroLabel <- ifelse(bsero=="BaselinePos", "baseline positive", 
                     ifelse(bsero=="BaselineNeg", "baseline negative", ""))

# temporary setting due to unknown reason for assays including bAb for id27hpvnAb
if (attr(config,"config")=="id27hpvnAb") {assays = assays[!grepl("bind", assays)]}

if(attr(config,"config")=="janssen_pooled_partA") {
  times_ = c("B","Day29","Day71","Mon6")
  labels.time = c("Day 1","Day 29", "Day 71", "Month 6"); names(labels.time) = times_
} else if (attr(config,"config")=="prevent19_stage2") {
  times_ = c("Day35","C1","BD1","DD1")
  labels.time = c("Day 35", "Crossover Day 1", "Booster Day 1", "Disease Day 1"); names(labels.time) = times_
} else if (attr(config,"config")=="azd1222_stage2") {
  times_ = c("Day57","Day90","Day180","Day360")
  labels.time = c("Day 57","Day 90", "Day 180", "Day 360"); names(labels.time) = times_
} else if (attr(config,"config")=="VaxArt_Mock") {
  times_ = c("B", "Day31", "Delta31overB", "Day91", "Day181", "Day366")
  labels.time = c("D01","D31", "D31 fold-rise over D01", "D91", "D181", "D366"); names(labels.time) = times_
} else if (attr(config,"config") %in% c("prevent19_stage2","prevent19nvx")) {
  times_ = c("Day35")
  labels.time = c("Day 35")
} else if (attr(config,"config")=="azd1222_stage2") {
  times_ = c("Day57","Day90","Day180","Day360")
  labels.time = c("Day 57", "Day 90","Day 180","Day 360")
} else {times_ = times 
} 

tps_no_delta_over_tinterm <-  times_[!times_ %in% c(paste0("Delta",timepoints[length(timepoints)],"over",timepoints[1]))] #c("B", "Day29", "Delta29overB", "Day57", "Delta57overB")
tps_no_delta_over_tinterm_lb <- if(attr(config,"config")=="vat08_combined") {c("Day 1_n","Day 1_nn", "Day 22_n", "Day 22_nn", "Day 43_n", "Day 43_nn", "D22 fold-rise over D1_n", "D22 fold-rise over D1_nn", "D43 fold-rise over D1_n", "D43 fold-rise over D1_nn")
  } else {labels.time[! grepl(paste0("over D",timepoints[1]),  labels.time)]}
tps_no_fold_change <- times_[!grepl("Delta", times_)]
tps_no_B_and_fold_change <- times_[!grepl("Delta", times_) & times_!="B"]

if (study_name == "VaxArt_Mock") {
    assays = assays[!grepl("nasal|saliva|T4|T8", assays)]
    assay_metadata = assay_metadata %>% filter(!grepl("nasal|saliva|T4|T8", assay))
    nextgen_output_flag = 1 # options: 3 (whole_report)  1 (BARDA_TLF)
} else {nextgen_output_flag = 999}

#if(file.exists(here::here('cor_graphical', paste0('report_', tolower(study_name), '.Rmd')))) {
  
#  message ("trial-specific report rmd found")
#  res = knitr::knit_child(c(here::here('cor_graphical', paste0('report_', tolower(study_name), '.Rmd'))), quiet = TRUE)
#  cat(res, sep = '\n')

#} else {
  #### COR folder postfix
  # for Sanofi, needs to loop through "", "omi"
  # for ENSEMBLE EUA, loop through "IncludeNotMolecConfirmed", "IncludeNotMolecConfirmedstart1"
  # for ENSEMBLE part A ancestral strain, loop through "SevereIncludeNotMolecConfirmed" or "ModerateIncludeNotMolecConfirmed" as needed
  # for ENSEMBLE part A variant, no loop, present adhoc figures
  # for other studies, loop through ""
  COR_postfix_list = ""
  if (study_name=="ENSEMBLE" & grepl("EUA", attr(config,"config"))) COR_postfix_list <- c("IncludeNotMolecConfirmed", "IncludeNotMolecConfirmedstart1")
  if (study_name=="ENSEMBLE" & grepl("partA$", attr(config,"config"))) COR_postfix_list <- c("IncludeNotMolecConfirmed") # ModerateIncludeNotMolecConfirmed SevereIncludeNotMolecConfirmed
  if (study_name=="ENSEMBLE" & attr(config,"config") == "janssen_partA_VL") COR_postfix_list <- c("adhoc")
  if (study_name=="IARCHPV") COR_postfix_list <- c("", "sus")
  if (attr(config,"config")=="prevent19_stage2") COR_postfix_list <- c("delta", "severe")
  if (attr(config,"config")=="azd1222_stage2") COR_postfix_list <- c("delta nab", "delta bab",
                                                                     "severe nab", "severe bab"
                                                                     )
  if (attr(config,"config") == "nvx_uk302") COR_postfix_list <- c("D35nvx_uk302")
  if (attr(config,"config") == "prevent19nvx") COR_postfix_list <- c("D35prevent19nvx")
  if (study_name=="VAT08") COR_postfix_list <- c("D22D43omi")
  if (study_name=="VaxArt_Mock") COR_postfix_list <- c("D31toM12_nextgen_mock_sera")
  if (study_name=="ILIAD_IB202P") COR_postfix_list <- c("C0iliad_ib202p_PPAI_C14only")

  if (COR_postfix_list == "adhoc"){ # only for config: janssen_partA_VL and COR: D29VLvariant
    
    COR = "D29VLvariant"
    COR_postfix_label=""
    
    tp="Day29"
    tp_lb="Day 29"
    trt_lb=": Vaccine Arm."
    trt="vaccine_bseroneg"
    
    #for (region in c("LA", "SA")) {
    #  for (marker in ("NAb" #,"Spike", "NAb_Spike"
    #                  )) {
    #              marker_lb = ifelse(marker=="NAb", "PsV-nAb ID50 Markers", ifelse(marker=="Spike", "Anti-Spike Binding Ab Markers", ifelse(marker=="NAb_Spike", "PsV-nAb ID50 and Anti-Spike Binding Ab Markers")))
                  
    #              pair_title_beginner = "Pairwise Correlation Matrix between "
    #    		      res = knitr::knit_child(c(here::here('cor_graphical', 'report_pair_variant.Rmd')), quiet = TRUE)
    #    		      cat(res, sep = '\n')
    #    		      cat("\\clearpage", sep = '\n')
        		      
    #  }
    #}
    
    for (region in c("LATAM", #"LATAM_pooled", 
                     "ZA"#, #"ZA_pooled"
                     )) {
      for (marker in c("nAb","bAb")) {
        		      res = knitr::knit_child(c(here::here('cor_graphical', 'report_rcdf_variant.Rmd')), quiet = TRUE)
        		      cat(res, sep = '\n')
        		      cat("\\clearpage", sep = '\n')
      }
    }
    
    
    for (region in c("LATAM", "ZA")) {
      for (marker in c("nAb", "bAb")) {
        		      res = knitr::knit_child(c(here::here('cor_graphical', 'report_spider_variant.Rmd')), quiet = TRUE)
        		      cat(res, sep = '\n')
        		      cat("\\clearpage", sep = '\n')
      }
    }
    
    for (region in c("LATAM", "ZA", "NAM")) {
      for (marker in c("nAb", "bAb")) {
        if (region=="NAM" && marker=="nAb") next
        		      res = knitr::knit_child(c(here::here('cor_graphical', 'report_violin_variant.Rmd')), quiet = TRUE)
        		      cat(res, sep = '\n')
        		      cat("\\clearpage", sep = '\n')
      }
    }
    
  } else if (study_name == "VAT08" | attr(config,"config") %in% c("prevent19_stage2","azd1222_stage2","nvx_uk302","prevent19nvx", "nextgen_mock", "iliad_ib202p")){
    
    for (COR_postfix in COR_postfix_list){
        
      # show in figure title
      COR_postfix_label = ""
      if (grepl("delta", COR_postfix)) COR_postfix_label=" (Delta Endpoint)"
      if (grepl("severe", COR_postfix)) COR_postfix_label=" (Severe Endpoint)"
      if (COR_postfix=="D22D43omi" & Trialstage_val == 1) COR_postfix_label= " (Stage1)"
      if (COR_postfix=="D22D43omi" & Trialstage_val == 2) COR_postfix_label= " (Stage2)"
      
      COR=case_when(COR_postfix=="" ~ "", 
                    COR_postfix=="delta" ~ "D35prevent19_stage2_delta", 
                    COR_postfix=="severe" ~ "D35prevent19_stage2_severe",
                    COR_postfix=="delta nab" ~ "D57azd1222_stage2_delta_nAb", 
                    COR_postfix=="delta bab" ~ "D57azd1222_stage2_delta_bAb", 
                    COR_postfix=="severe nab" ~ "D57azd1222_stage2_severe_nAb", 
                    COR_postfix=="severe bab" ~ "D57azd1222_stage2_severe_bAb",
                    !is.na(COR_postfix) ~ COR_postfix
                    )
      
      # SET 1
cat("## Violin plots by case status\n\n")
cat("\\clearpage", sep = '\n')
      
      for (a in if (study_name == "ILIAD_IB202P") {assays} else if (study_name == "VaxArt_Mock") {c(if (nextgen_output_flag == 1) assays[2], if (nextgen_output_flag == 3) assays[!grepl("IgA", assays)])
        } else {c("pseudoneutid50", if(attr(config,"config")!="prevent19_stage2") "bindSpike", if(attr(config,"config") %in% c("prevent19_stage2","azd1222_stage2")) "bindSpike_sub_stage2")}){
             
        if ((grepl("nab", COR_postfix) & !grepl("pseudoneutid50", a)) | (grepl("bab", COR_postfix) & !grepl("bindSpike", a))) next # for AZ stage 2
        if (a == "pseudoneutid50" & attr(config,"config") %in% c("nvx_uk302","prevent19nvx")) next # no id50 for nvx_uk302, prevent19nvx
    
        for (tp in if (study_name %in% c("VaxArt_Mock", "ILIAD_IB202P")) {tps_no_delta_over_tinterm_lb[1:3]} else {tps_no_delta_over_tinterm_lb}){
          
          if(attr(config,"config")=="azd1222_stage2" & tp=="Day 360") next # do not have this for azd1222_stage2
          
          tpLabel = gsub("_n", " naive", gsub("_nn", " non naive", tolower(tp)))
          if (study_name == "VaxArt_Mock") {
            tpLabel = case_when(tp == "Day 01" ~ "D01",
                                tp == "Day 31" ~ "D31",
                                tp == "D31 fold-rise over D1" ~ "fold-change (D31/D01)",
                                TRUE ~ tpLabel)
          }
          aLabel = gsub("_sub_stage2", " subset", a)
          if (study_name == "VaxArt_Mock") {
            aLabel = paste0(
              gsub("Serum Binding IgG Antibody to ", "bAb-IgG ", 
                          gsub("Serum neutralization to |Serum neutralization ", "nAb ID50 ", 
                              gsub("Spike D614", "Spike Index", labels.assays[a]))),
              ifelse(grepl("bind", a), " concentrations", ""))
          } else {aLabel = labels.assays[a]}
          
          specimen_type <- paste0("based on ", ifelse(grepl("sera", a), "sera", ifelse(grepl("nasal", a), "nasal fluid", ifelse(grepl("saliva", a), "saliva", "PBMC"))))
          cohort_name <- paste0("(ccIAS-", ifelse(grepl("sera", a), "sera", ifelse(grepl("nasal", a), "nasal fluid", ifelse(grepl("saliva", a), "saliva", "PBMC"))), "). ")
                    
          res = knitr::knit_child(c(here::here('cor_graphical', 'report_set1.Rmd')), quiet = TRUE)
          cat(res, sep = '\n')
          cat("\\clearpage", sep = '\n')
        }
      }
      
      # adhoc for vat08 stage 2 non-naive at day 43 and day 43 over day 1, by S-pos and Prev-inf
      if (attr(config,"config")=="vat08_combined" & COR_postfix_list == "D22D43omi"){
        if (Trialstage_val == 1) next # this is only for stage 2
        
        for (a in c("pseudoneutid50", "bindSpike")) {
         
          for (tp in c("Day 43_nn_s_pos", "D43 fold-rise over D1_nn_s_pos", "Day 43_nn_prev_inf", "D43 fold-rise over D1_nn_prev_inf")){
            
              tpLabel = gsub("_s_pos", " S-pos only", gsub("_prev_inf", " Prev-inf", gsub("_n", " naive", gsub("_nn", " non naive", tolower(tp)))))
              aLabel = a 
              res = knitr::knit_child(c(here::here('cor_graphical', 'report_set1.Rmd')), quiet = TRUE)
              cat(res, sep = '\n')
              cat("\\clearpage", sep = '\n')
          }
        }
      }
      
      # adhoc for vat08 stage 2 non-naive at day 1, by S-pos and Prev-inf
      if (attr(config,"config")=="vat08_combined" & COR_postfix_list == "D22D43omi"){
        if (Trialstage_val == 1) next # this is only for stage 2
        
        for (a in c("pseudoneutid50", "bindSpike")) {
         
          for (tp in c("Day 1_nn_s_pos", "Day 1_nn_prev_inf")){
            
              tpLabel = gsub("_s_pos", " S-pos only", gsub("_prev_inf", " Prev-inf", gsub("_n", " naive", gsub("_nn", " non naive", tolower(tp)))))
              aLabel = a 
              res = knitr::knit_child(c(here::here('cor_graphical', 'report_set1.Rmd')), quiet = TRUE)
              cat(res, sep = '\n')
              cat("\\clearpage", sep = '\n')
          }
        }
      }
      
      # adhoc for vat08 stage 2 non-naive at day 1 and day 43, for S-pos and region overlaid
      if (attr(config,"config")=="vat08_combined" & COR_postfix_list == "D22D43omi"){
        if (Trialstage_val == 1) next # this is only for stage 2
        
        for (a in c("bindSpike")) {
         
          for (tp in c("Day 1_nn_s_pos_region", "Day 43_nn_s_pos_region")){
            
              tpLabel = gsub("_s_pos", " S-pos only", gsub("_nn", " non naive", gsub("_region", ", by region", tolower(tp))))
              aLabel = a 
              res = knitr::knit_child(c(here::here('cor_graphical', 'report_set1.Rmd')), quiet = TRUE)
              cat(res, sep = '\n')
              cat("\\clearpage", sep = '\n')
          }
        }
      }
      
      if (attr(config,"config") == "nvx_uk302") next # break the loop for nvx_uk302

      # SET 2
cat("## Longitudinal plots\n\n")
cat("\\clearpage", sep = '\n')
      
      assay_grp_list = if(attr(config,"config")=="vat08_combined"){
        c(paste0(assays[!assays=="bindSpike_mdw"][1:2], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][3:4], collapse="_"), 
                          paste0(assays[!assays=="bindSpike_mdw"][5:6], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][7:8], collapse="_"),
                          "bindSpike_mdw",
                          paste0(assays[!assays=="bindSpike_mdw"][9:10], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][11:12], collapse="_"),
                          paste0(assays[!assays=="bindSpike_mdw"][13:14], collapse="_")
        )} else if (attr(config,"config")=="prevent19_stage2"){
          c("pseudoneutid50_D614G_pseudoneutid50_Delta","bindSpike_D614_bindSpike_Delta1")
        } else if (grepl("bab", COR_postfix)){ # for azd1222_stage2
          assays[grepl("bindSpike", assays)]
        } else if (grepl("nab", COR_postfix)){ # for azd1222_stage2
          assays[grepl("pseudoneutid50", assays)]
        } else if (study_name == "VaxArt_Mock") {
          c(if (nextgen_output_flag == 1) assays[2], if (nextgen_output_flag == 3) assays[!grepl("mdw", assays)])
        } else {assays}
      
      for (version in c("", if (COR_postfix_list == "D22D43omi" & Trialstage_val == 2) "_v2")){
        for (assay_grp in assay_grp_list){
          for (tm in c(if(attr(config, "config") == "VaxArt_Mock" & nextgen_output_flag == 3) "Day initial", "Day whole")){
            for (case_type in c("default", if (attr(config, "config") == "VaxArt_Mock" & nextgen_output_flag == 3) c("proximal", "distal"))){
            
              if (attr(config,"config") == "prevent19nvx") next # no need for prevent19nvx
    
              aLabel = paste0(
                  gsub("Serum Binding IgG Antibody to ", "bAb-IgG ", 
                              gsub("Serum neutralization to |Serum neutralization ", "nAb ID50 ", 
                                  gsub("Spike D614", "Spike Index", labels.assays[assay_grp]))),
                  ifelse(grepl("bind", assay_grp), " concentrations", ""))
              
              specimen_type <- paste0("based on ", ifelse(grepl("sera", assay_grp), "sera", ifelse(grepl("nasal", assay_grp), "nasal fluid", ifelse(grepl("saliva", assay_grp), "saliva", "PBMC"))))
              cohort_name <- paste0("(ccIAS-", ifelse(grepl("sera", assay_grp), "sera", ifelse(grepl("nasal", assay_grp), "nasal fluid", ifelse(grepl("saliva", assay_grp), "saliva", "PBMC"))), "). ")
            
              res = knitr::knit_child(c(here::here('cor_graphical', 'report_set2.Rmd')), quiet = TRUE)
              cat(res, sep = '\n')
              cat("\\clearpage", sep = '\n')
            }
          }
            
        }
      }
      
      if (attr(config,"config") == "nextgen_mock") next # break the loop for VaxArt_Mock
      
      # SET 3
cat("## Correlation plots across assays\n\n")
cat("\\clearpage", sep = '\n')
      
      if (COR=="D57azd1222_stage2_delta_bAb") {
        # adhoc figure
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_set3_az_adhoc.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
      }
      
      for (bsero in c("non_naive")){
        if (attr(config,"config") %in% c("prevent19_stage2","azd1222_stage2","prevent19nvx")) next # prevent19_stage2, azd1222_stage2, prevent19nvx don't have non_naive
        if (attr(config,"config") == "iliad_ib202p") bsero = ""
        
          for (trt in if (attr(config,"config") == "iliad_ib202p") {c("vac", "pla")} else c("vac_pla")){
              
              for (tp in if(attr(config,"config")=="vat08_combined") {tps_no_delta_over_tinterm} else {tps_no_fold_change}){
                
                for (assay_n in c(length(assays), 
                                  if (attr(config,"config") == "vat08_combined") 9, 
                                  if (attr(config,"config") == "vat08_combined") 6,
                                  if (attr(config,"config") == "vat08_combined") 10, 
                                  if (attr(config,"config") == "vat08_combined") 7)){
                  
                  tpLabel = ifelse(tp=="B", "Day1", tp)
                  res = knitr::knit_child(c(here::here('cor_graphical', 'report_set3.Rmd')), quiet = TRUE)
                  cat(res, sep = '\n')
                  cat("\\clearpage", sep = '\n')
                }
              }
          }
      }
      
      for (bsero in c("naive")){
        
        if (attr(config,"config") == "iliad_ib202p") next
          
          for (trt in c("vac")){
              
              for (tp in if (attr(config,"config")=="prevent19_stage2") {c("Day35","Day35_sub")
                } else if (attr(config,"config")=="vat08_combined") {tps_no_delta_over_tinterm[2:5]
                  } else {tps_no_B_and_fold_change}){
                  
                  
                  assay_n = ifelse(COR %in% c("D57azd1222_stage2_delta_nAb", "D57azd1222_stage2_severe_nAb"), sum(grepl("pseudoneutid50", assays)),
                                   ifelse(COR %in% c("D57azd1222_stage2_delta_bAb", "D57azd1222_stage2_severe_bAb"), sum(grepl("bindSpike", assays)),
                                      length(assays)))
                  if (tp == "Day35_sub"){assay_n = 4; tp = "Day35" 
                  # hard code to pool a subset pair plot for prevent19_stage2 
                  } else {assay_n = length(assays)}  
                  
                  for (assay_n in c(assay_n, 
                                  if (attr(config,"config") == "vat08_combined") 9, 
                                  if (attr(config,"config") == "vat08_combined") 6,
                                  if (attr(config,"config") == "vat08_combined") 10, 
                                  if (attr(config,"config") == "vat08_combined") 7)) {
                  
                    tpLabel = ifelse(tp=="B", "Day1", tp)
                    
                    res = knitr::knit_child(c(here::here('cor_graphical', 'report_set3.Rmd')), quiet = TRUE)
                    cat(res, sep = '\n')
                    cat("\\clearpage", sep = '\n')
                  }
              }
          }
      }
      
      if (attr(config,"config") == "prevent19nvx") next # break the loop for prevent19nvx
      
      # SET 4
cat("## Correlation plots across timepoints\n\n")
cat("\\clearpage", sep = '\n')

      for (a in assays){
          
          if ((grepl("nab", COR_postfix) & !grepl("pseudoneutid50", a)) | (grepl("bab", COR_postfix) & !grepl("bindSpike", a)) ) next # for AZ stage 2
        
          res = knitr::knit_child(c(here::here('cor_graphical', 'report_set4.Rmd')), quiet = TRUE)
          cat(res, sep = '\n')
          cat("\\clearpage", sep = '\n')
          
      }
      
      # adhoc for vat08 stage 1
      if (attr(config,"config") == "vat08_combined" & COR_postfix_list == "D22D43omi"){
        if (Trialstage_val == 2) next # this is only for stage 1
        
        for (sanofi_filter in c("sanofi_us_only", "sanofi_all_country")){
          
          sanofi_lb = ifelse(sanofi_filter == "sanofi_us_only", " (U.S only)", 
                             ifelse(sanofi_filter == "sanofi_all_country", " (All Countries)"))
          
          for (a in c("pseudoneutid50","pseudoneutid50_B.1.351","pseudoneutid50_BA.1",
                      "pseudoneutid50_BA.2","pseudoneutid50_BA.4.5","pseudoneutid50_mdw")){
            
            res = knitr::knit_child(c(here::here('cor_graphical', 'report_set1_sanofi_vat08.Rmd')), quiet = TRUE)
            cat(res, sep = '\n')
            cat("\\clearpage", sep = '\n')
          }
        }
      }
  }
    
    

  } else if (study_name=="COVAIL"){
  
  assay_metadata <- assay_metadata %>% filter(panel=="id50")
  assays <- assay_metadata$assay

  set1_panels_1 = c("id50")
  set1_group_1= c(" (13 one-dose mRNA booster arms pooled)",
                  " (13 one-dose mRNA booster arms pooled: naive vs. non-naive)",
                  " (3 Sanofi booster arms pooled)",
                  " (mRNA Moderna vs. mRNA Pfizer)",
                  " (mRNA Prototype vs. mRNA Omicron-Containing)",
                  " (Moderna: mRNA Prototype vs. mRNA Omicron-Containing)",
                  " (Pfizer: mRNA Prototype vs. mRNA Omicron-Containing)",
                  " (mRNA Bivalent vs. mRNA Monovalent)")
  set1_group_2= c(" (13 one-dose mRNA booster arms pooled)", " (3 Sanofi booster arms pooled)")

  set1_times <- c("B","Day15","Delta15overB")
  
  set2_times = c("B","Day15","Day29","Day91")
  
  
  ## Set 1: violin and line plots #############
  for (strain in c("6_strain")){
    for (panel in set1_panels_1){
      for (group in set1_group_1){
        for (time in set1_times) {
        
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub1.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
        }
      }
    }
    }

  ## Set 3: Correlation plots across markers at a given time point #############
  for (time in set2_times) {
    for (strain in c("6_markers")){
      for (group in set1_group_2){
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub3.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
      }
    }
    }

  ## Set 4: Correlation plots for a given marker across time points #############
  for (assay in assays) {
    for (group in set1_group_2){
        res = knitr::knit_child(c(here::here('cor_graphical', 'report_sub4.Rmd')), quiet = TRUE)
        cat(res, sep = '\n')
        cat("\\clearpage", sep = '\n')
    }
  }

} else { # for all other studies but config: janssen_partA_VL and COR: D29variant
  
    for (COR_postfix in COR_postfix_list){
        
      # show in figure title
      COR_postfix_label = ""
      if (COR_postfix == "IncludeNotMolecConfirmedstart1") COR_postfix_label=" (start1)"
      if (COR_postfix == "ModerateIncludeNotMolecConfirmed") COR_postfix_label=" (Moderate Endpoint)"
      if (COR_postfix == "SevereIncludeNotMolecConfirmed") COR_postfix_label=" (Severe Endpoint)"
      if (COR_postfix == "omi") COR_postfix_label=" (Omicron Endpoint)"
      if (COR_postfix == "sus") COR_postfix_label=" (sus)"
  
      
      if (study_name=="IARCHPV"){
        
        COR=ifelse(COR_postfix=="", "M18", "M18sus")
        trt.labels <- c("Single-dose","Two-dose","Two doses default","Three-dose")
        trt.labels2 <- c("Single-dose","Two-dose (Days 1 and =180)","Two doses default (Days 1 and 60)","Three-dose (Days 1, 60 and =180)")
    
    
        ########################################### Pair plots ###########################################
        region=""
        tp=COR
        tp_lb=COR
        
        trt = "pooled"
        trt_lb = ""  
          
        for (marker in c("BAb","NAb", "some_BAb","some_NAb")){
          
          if (!grepl("pseudoneutid50", assays) && grepl("NAb", marker)) next
          if (!grepl("bind", assays) && grepl("BAb", marker)) next
          
          pair_title_beginner = ifelse(!grepl("some", marker), "Pairwise Correlation Matrix between ", "Pairwise Correlations of ")
          marker_lb = ifelse(marker=="BAb", "Binding Ab Markers", ifelse(marker=="NAb", "PsV-nAb ID50 Markers", ifelse(marker=="some_BAb", "Binding Ab Markers to HPV Strains 6, 11, 16, 18, 31 and IgG Score", ifelse(marker=="some_NAb", "PsV-nAb ID50 Markers to HPV Strains 6, 11, 16, 18, 31 and
PsV-nAb ID50 Score"))))
            
          res = knitr::knit_child(c(here::here('cor_graphical', 'report_pair_variant.Rmd')), quiet = TRUE)
          cat(res, sep = '\n')
          cat("\\clearpage", sep = '\n')
        }
        ############################################# Violin plots ###########################################
        
        facet=""
        ver="v1"
        type="Violinbox"
        for (trt_order in c(1,2,4,3,5)) {
  		    for (assay_long in assays) {
  		      for (casetype in c("AnyHPV", "HPV11", "HPV18", "HPV31", "HPV6", "HPV16", 
  		                         "HPV11OtherHPV", "HPV18OtherHPV", "HPV31OtherHPV", "HPV6OtherHPV", "HPV16OtherHPV")){# overall or breakthrough of specific type
  		        
  		        # skip if specific case type doesn't match with plot type
              if (casetype!="AnyHPV" & !grepl(gsub("OtherHPV", "", casetype), assay_long)) next
  		        
  		        #if (!grepl("pseudoneutid50", assays) && grepl("pseudoneutid50", assay_long)) next
              #if (!grepl("bind", assays) && grepl("bind", assay_long)) next
  		        
    		      assay = gsub("bind_", "", gsub("pseudoneut","pnAb_", assay_long))
    	    
    	        
    	        trt = c("pooled", trt.labels)[trt_order]
              trt_lb = c("pooled", trt.labels2)[trt_order]
    	        
    	        res = knitr::knit_child(c(here::here('cor_graphical', 'report_violin.Rmd')), quiet = TRUE)
    	        cat(res, sep = '\n')
    	        cat("\\clearpage", sep = '\n')
  		      }
  	      }
  	    }
	      
        		      
      } else {
        ########################################### Boxplots ########################################### 
        
        # Eventually will have to loop through assays, and combine each individual assay's boxplots into one figure
        for(time in timepoints) {
          if (attr(config,"config")=="janssen_pooled_partA") next
          
          tps <- times[gsub("[^\\d]+", "", times, perl=TRUE)==time]
          tpsLabels <- labels.time[tps]
          COR = currCOR <- paste0("D",time, COR_postfix)
          
          for (tpNum in seq(tps)) { #eg: seq(tps) - Day 22, Delta22overB
            
            tp <- tps[tpNum]
            tpLabel <- tpsLabels[tpNum]
            lineText <- ifelse(grepl("Delta", tp), "", " The three dashed lines in each figure are ULOQ, LLOQ, and LLOD, from top to bottom respectively.")
            
            res = knitr::knit_child(c(here::here('cor_graphical', 'report_boxplots.Rmd')), quiet = TRUE)
            cat(res, sep = '\n')
            cat("\\clearpage", sep = '\n')
          }
        }
        
        ########################################### Weighted RCDF plots ########################################### 
        
        # Eventually will have to loop through assays, and combine each individual assay's RCDFs into one figure
        for(time in timepoints) {
          if (attr(config,"config")=="janssen_pooled_partA") next
          
          tps <- times[gsub("[^\\d]+", "", times, perl=TRUE)==time]
          tpsLabels <- labels.time[tps]
          COR = currCOR <- paste0("D",time, COR_postfix)
          
          for (tpNum in seq(tps)) {
            
            tp <- tps[tpNum]
            tpLabel <- tpsLabels[tpNum]
            
            res = knitr::knit_child(c(here::here('cor_graphical', 'report_marker_rcdf.Rmd')), quiet = TRUE)
            cat(res, sep = '\n')
            cat("\\clearpage", sep = '\n')
          }
        }
        
        ############## Weighted RCDF plots of threshold correlate concentration for vaccine efficacy ########################## 
        
        assay.labels <- sapply(assays, function(assay) {
          if(grepl("bind", assay)) { return ( paste0( gsub("bind", "anti-", assay), " binding Ab") ) } 
          else if(grepl("pseudoneutid", assay)) { return ( gsub("pseudoneutid", "PsV-nAb ID", assay) ) } 
          else return (assay)
        })
        
        # Only show figures if there are substantial cases
        # (I haven't seen a scenario where there aren't, but keeping this from Kendrick)
        for(time in timepoints) {
          if (attr(config,"config")=="janssen_pooled_partA") next
          
          tps <- times[gsub("[^\\d]+", "", times, perl=TRUE)==time]
          tpsLabels <- labels.time[tps]
          tp <- tps[!grepl("Delta", tps)]
          tpLabel <- tpsLabels[!grepl("Delta", tps)]
          COR = currCOR <- paste0("D",time, COR_postfix)
          
          if(sum(plot_ve_curves)>0){ # plot_ve_curves = c(1, 1) for base neg and base pos, if one doesn't exist, set to 0, eg: c(0, 1)
            for (assayNum in seq(assays)) {

              assay <- assays[assayNum]
              assayLabel <- assay.labels[assayNum]

              res = knitr::knit_child(c(here::here('cor_graphical', 'report_rcdf.Rmd')), quiet = TRUE)
              cat(res, sep = '\n')
              cat("\\clearpage", sep = '\n')
            }
          }
        }
        
        
        ############################################# Violin and line plots ############################################
        
        facets <- c("", "Age", "Risk", "Age_Risk", "Sex", "RaceEthnic", "Dich_RaceEthnic")
        names(facets) <- c("", "age", "risk condition", "age and risk condition", "sex assigned at birth", "race and ethnic group", "dichotomous classification of race and ethnic group")
        
        #for (sev in c("", if (study_name=="ENSEMBLE" | study_name=="MockENSEMBLE") "severe")){
        # comment out on 4/7/2023 because only ENSEMBLE partA primary manuscript needs to be looped through "sev" 
          for (facet in facets) {
          	for (ver in c("v1", "v2", if(do.fold.change==1)"v3")) {
          		for (type in c("Linebox", "Violinbox")) {
          		  for (assay_long in assays) {
          		    assay = gsub("bind", "", gsub("bind", "", gsub("bind", "", gsub("pseudoneut","pnAb_", assay_long))))
          		    for (trt in c("Placebo", "Vaccine")) {
                    if (length(timepoints)==1){COR=paste0("D",timepoints, COR_postfix)} else {COR=paste0("D",paste(timepoints, collapse="D"), COR_postfix)}
          		        
          		      trt_lb = trt
          		      casetype = ""
          		      res = knitr::knit_child(c(here::here('cor_graphical', 'report_violin.Rmd')), quiet = TRUE)
          		      cat(res, sep = '\n')
          		      cat("\\clearpage", sep = '\n')
          		    }
          		  }
              }
          	}
          }
        #}
        
        ###################################################### Scatter plots ###################################################
        
        labels.time.no.fold <- labels.time[(names(labels.time) %in% times) & !grepl("fold-rise", labels.time)]
        
        # (sev in c("", if (study_name=="ENSEMBLE" | study_name=="MockENSEMBLE") "severe")){
        # comment out on 4/7/2023 because only ENSEMBLE partA primary manuscript needs to be looped through "sev" 
          for (cohort in c("Vaccine", "all")) {
          	for (assay_long in assays) {
          	  assay = gsub("bind", "", gsub("bind", "", gsub("bind", "", gsub("pseudoneut","pnAb_", assay_long))))
              for (day in gsub(" ","", labels.time.no.fold)) {
                if (length(timepoints)==1){COR=paste0("D",timepoints, COR_postfix)} else {COR=paste0("D",paste(timepoints, collapse="D"), COR_postfix)}
          		  res = knitr::knit_child(c(here::here('cor_graphical', 'report_scatter1.Rmd')), quiet = TRUE)
            		cat(res, sep = '\n')
                cat("\\clearpage", sep = '\n')
          		} 
          	}
          }
        #}
        
        #for (sev in c("", if (study_name=="ENSEMBLE" | study_name=="MockENSEMBLE") "severe")){
        # comment out on 4/7/2023 because only ENSEMBLE partA primary manuscript needs to be looped through "sev" 
          for (cohort in c("Vaccine", "all")){
          	for (assay_long in assays){
          	  assay = gsub("bind", "", gsub("bind", "", gsub("bind", "", gsub("pseudoneut","pnAb_", assay_long))))
              if (length(timepoints)==1){COR=paste0("D",timepoints, COR_postfix)} else {COR=paste0("D",paste(timepoints, collapse="D"), COR_postfix)}
          	  res = knitr::knit_child(c(here::here('cor_graphical', 'report_scatter2.Rmd')), quiet = TRUE)
          		cat(res, sep = '\n')
              cat("\\clearpage", sep = '\n')
          	}
          }
        
          ############################################## adhoc longitudinal violin plots (for manuscript reviewers) ############
        
        for (asy in c("RBD","Spike","pnAb_id50")){
          
              asy_lb = case_when(asy=="RBD" ~ "bindRBD",
                                 asy=="Spike" ~ "",
                                 asy=="pnAb_id50" ~ "")
          	  res = knitr::knit_child(c(here::here('cor_graphical', 'report_violin_adhoc.Rmd')), quiet = TRUE)
          		cat(res, sep = '\n')
              cat("\\clearpage", sep = '\n')
          	}
      }
    }
  }

  #}
#}
  



```
