```{r, echo = FALSE}
if(COR == "D29IncludeNotMolecConfirmed"){
  info <- paste0(
    "Day 29 analysis including non-molecularly confirmed endpoints starting ",
    "seven days after first dose."
  )
  title <- "Seven days after first dose"
}else if(COR == "D29IncludeNotMolecConfirmedstart1"){
  info <- paste0(
    "Day 29 analysis including non-molecularly confirmed endpoints starting ",
    "one day after first dose."
  )
  title <- "One day after first dose"
}else if(COR == "D29"){
  info <- "Day 29 analysis"
  title <- "Day 29"
}

```

## `r title`

This section contains results from the `r info`.

```{r, results = "asis"}
here::i_am("cop_mediation/report_sub.Rmd")
if(config$study_name_code == "ENSEMBLE"){
  full_result <- readRDS(here::here("cop_mediation", "output",
    paste0("full_result_janssen_pooled_real_", COR, ".rds")
  ))
  # adcp_result <- readRDS(here::here("cop_mediation", "output",
  #   paste0("full_result_janssen_pooled_realADCP_", COR, ".rds")
  # ))
  # psv_result <- readRDS(here::here("cop_mediation", "output",
  #   paste0("full_result_janssen_pooled_realPsV_", COR, ".rds")
  # ))
  # full_result <- rbind(bind_result, psv_result) #, adcp_result)
}else if(config$study_name_code == "COVE"){
  full_result <- readRDS(here::here("cop_mediation", "output",
    paste0("full_result_moderna_real_", COR, ".rds")
  ))
}

init_kable <- knitr::kable(full_result, 
            format = "latex", row.names = FALSE, booktabs = TRUE, escape = FALSE,
            caption = paste0("Table of mediation effect estimates for quantitative markers with 95\\% confidence intervals. \\newline{} Direct VE = VE comparing vaccine vs. placebo with marker set to distribution in placebo. \\newline{} Indirect VE = VE in vaccinated comparing observed marker vs. hypothetical marker under placebo. \\newline{} Prop. mediated = fraction of total risk reduction from vaccine attributed to antibody response."),
            linesep = c(rep("", length(assays)-1), "\\hline"))
if(any(is.na(full_result))){
	init_kable <- kableExtra::add_footnote(init_kable, "NA denotes insufficient overlap in antibody response between vaccinated and control participants.")
}
kableExtra::kable_styling(init_kable, latex_options = c("scale_down", "HOLD_position"))
```

\clearpage

### Basic statistics on cases

```{r}
summary_stats <- readRDS(
  here::here("cop_mediation", "output", 
    paste0("summary_stats_", attr(config,"config"),
           "_", COR, ".rds")
  )
)

if(config$study_name_code == "ENSEMBLE"){
  # summary_stats_ADCP <- readRDS(
  #   here::here("cop_mediation", "output", 
  #     paste0("summary_stats_janssen_pooled_realADCP_", COR, ".rds")
  #   )
  # )
  summary_stats_PsV <- readRDS(
    here::here("cop_mediation", "output", 
    paste0("summary_stats_janssen_pooled_real_", 
           COR, ".rds"))
  )
  base_caption <- "Endpoints included in phase 2 by study arm, binding analysis "
  base_caption2 <- "Total endpoints by study arm in binding data set "
}else if(config$study_name_code == "COVE"){
  base_caption <- "Endpoints included in phase 2 by study arm"
  base_caption2 <- "Total endpoints by study arm"
}
is_start1 <- grepl("start1", COR)
```

```{r}
kableExtra::kable_styling(
  knitr::kable(summary_stats$tab1, caption = paste0(base_caption, ifelse(is_start1, "starting 1 day after Day 29", ""))),
  latex_options = "HOLD_position"
)

if(config$study_name_code == "ENSEMBLE"){
  # kableExtra::kable_styling(
  #   knitr::kable(summary_stats_ADCP$tab1, caption = paste0("Endpoints included in phase 2 by study arm, ADCP analysis", ifelse(is_start1, "starting 1 day after Day 29", ""))),
  #   latex_options = "HOLD_position"
  # )

  kableExtra::kable_styling(
    knitr::kable(summary_stats_PsV$tab1, caption = paste0("Endpoints included in phase 2 by study arm, PsV analysis", ifelse(is_start1, "starting 1 day after Day 29", ""))),
    latex_options = "HOLD_position"
  )
}
```

\clearpage


```{r}
kableExtra::kable_styling(
  knitr::kable(summary_stats$tab2, caption = paste0(base_caption2, ifelse(is_start1, "starting 1 day after Day 29", ""))),
  latex_options = "HOLD_position"
)

if(study_name_code == "ENSEMBLE"){
  # kableExtra::kable_styling(
  #   knitr::kable(summary_stats_ADCP$tab2, caption = paste0("Total endpoints by study arm in ADCP data set ", ifelse(is_start1, "starting 1 day after Day 29", ""))),
  #   latex_options = "HOLD_position"
  # )

  kableExtra::kable_styling(
    knitr::kable(summary_stats_PsV$tab2, caption = paste0("Total endpoints by study arm in PsV data set ", ifelse(is_start1, "starting 1 day after Day 29", ""))),
    latex_options = "HOLD_position"
  )
}
```

\clearpage


```{r}
if(config$study_name_code == "ENSEMBLE"){
  assay <- c("Binding", 
             # "ADCP", 
             "PsV")
  day <- c(summary_stats$day_of_analysis,
           # summary_stats_ADCP$day_of_analysis,
           summary_stats_PsV$day_of_analysis)  
}else if(config$study_name_code == "COVE"){
  assay <- "All assays"
  day <- summary_stats$day_of_analysis
}

kableExtra::kable_styling(
  knitr::kable(data.frame(Assay = assay, `Analysis day` = day ),
             caption = "The day used to generate binary endpoints in the mediation analysis"),
  latex_options = "HOLD_position"
)
```
