---
header-includes:
   - \usepackage{float}
   
title: "`r ifelse(Sys.getenv('TRIAL') == 'janssen_pooled_partA', 'ENSEMBLE Optimal Surrogate Analysis Report: janssen_pooled_partA', 
    ifelse(Sys.getenv('TRIAL') == 'janssen_la_partA', 'ENSEMBLE Optimal Surrogate Analysis Report: janssen_la_partA', 
    ifelse(Sys.getenv('TRIAL') == 'covail_tcell', 'COVAIL Optimal Surrogate Analysis Report', 
    ifelse(Sys.getenv('TRIAL') == 'covail_xassays', 'COVAIL SeromYx Optimal Surrogate Analysis Report', 
    'NA'))))`"
                     
subtitle: "`r Sys.Date()`"

output:
  pdf_document: default
  html_document: default
  citation_package: natbib   
  number_sections: true
  extra_dependencies: ["caption", "subcaption", "graphicx"]
  toc: true
---






```{r, include = FALSE}
library(here)
here::i_am("cor_surrogates/report.Rmd")
```

<!-- \tableofcontents -->

```{r, child=here("cor_surrogates", 'report_sub_covail_xassays.Rmd')}
```


<!-- BEFORE KNITTING report.Rmd  DEFINE AND RUN THE FOLLOWING IN RSTUDIO: -->
<!-- Sys.setenv(TRIAL = "covail_xassays") -->
<!-- Sys.setenv(file_path = "/home/bborate/forked_correlates_directory/correlates_reporting2/cor_surrogates/output/covail_xassays/naive_1dosemRNA_proximal_bRiskFactors") -->


<!-- Naive cohort       -->
<!-- <!-- Non-Naive cohort   --> -->
<!-- <!-- One-dose mRNA vaccine arms (1-2, 4-12)     --> -->
<!-- One-dose vaccine arms (1-2, 4-15)       -->
<!-- <!-- Proximal cases       --> -->
<!-- All cases      -->
<!-- <!-- Reference Model uses risk score only --> -->
<!-- <!-- Reference Model uses bRiskFactors only     --> -->
<!-- Reference Model uses bRiskFactors + insert + stage info      -->




<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dosemRNA_proximalcases_bRiskFactors.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dosemRNA_proximalcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dose_proximalcases_bRiskFactors.Rmd')} -->
<!-- ``` -->



<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dose_proximalcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dosemRNA_allcases_bRiskFactors.Rmd')} -->
<!-- ``` -->




<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dosemRNA_allcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->




<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dose_allcases_bRiskFactors.Rmd')} -->
<!-- ``` -->




<!-- ```{r, child=here("cor_surrogates", 'report_sub_covailxassays_naive_1dose_allcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->




<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_naive_1dosemRNA_proximalcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->

<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_naive_1dosemRNA_allcases_bRiskFactors.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_naive_1dosemRNA_allcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_naive_1dose_proximalcases_bRiskFactors.Rmd')} -->
<!-- ``` -->



<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_naive_1dose_proximalcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->



<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_naive_1dose_allcases_bRiskFactors.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_naive_1dose_allcases_bRiskFactors.insert.stage.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_non-naive_1dosemRNA_allcases_riskscore.Rmd')} -->
<!-- ``` -->


<!-- ```{r, child=here("cor_surrogates", 'report_sub_covail_non-naive_1dose_allcases_riskscore.Rmd')} -->
<!-- ``` -->

