---
title: "CoR Coxph Meta and Collate Report"
shorttitle: "Coxph Meta Collate"
author:
header-includes:
   - \usepackage{float}
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    citation_package: natbib
    number_sections: true
    extra_dependencies: ["caption", "subcaption", "graphicx"]
    toc: false
linkcolor: blue
bibliography: ref.bib
---

```{r, include=FALSE}
renv::activate(project = here::here(".."))    
Sys.setenv("TRIAL"="janssen_pooled_EUA")
source(here::here("..", "_common.R"), local = knitr::knit_global()) # needed for collate coxph tables
```


\counterwithin{table}{section}
\counterwithin{figure}{section}

\clearpage




# Univariate Cox Models of Risk: Hazard Ratios

```{r, echo=FALSE, results='asis'}

covariates_adjusted = covariates_riskscore
covariates_adjusted = sub("\\~\\.\\+","",covariates_adjusted)
covariates_adjusted = sub("_","",covariates_adjusted)

for (i in 1:2) {
    COR <- ifelse(i==1, "D29IncludeNotMolecConfirmed", "D29IncludeNotMolecConfirmedstart1")
    config.cor <- config::get(config = COR)
    for(opt in names(config.cor)) eval(parse(text = paste0(names(config.cor[opt])," <- config.cor[[opt]]")))
    special.note = paste0("$\\ddagger$ Count cases starting ", ifelse(i==1,7,1), " days post Day 29.")
    pathCoRoutput <- paste0("output/janssen_pooled_EUA/", COR) # it does not matter which TRIAL we use here
    res = knitr::knit_child(c(here::here('meta_collate_sub0.Rmd')), quiet = TRUE)
    cat(res, sep = '\n')
}
  


```
