---
knit: "bookdown::render_book"
title: '`r source(here::here("../_common.R")); paste(study_name, "Correlates Analyses Report")`'  
author: '`r paste(study_name, "Biostatistics Team")`'
date: "`r format(Sys.time(), '%B %d, %Y')`"
documentclass: book
site: bookdown::bookdown_site
bibliography: [book.bib, packages.bib]
biblio-style: apalike
suppress-bibliography: true
link-citations: yes
colorlinks: yes
graphics: yes
lot: yes
lof: yes
always_allow_html: yes
toc_depth: 5
header-includes:
   - \usepackage{eso-pic,graphicx,transparent,caption,pdflscape,titling} # keep titling last!
   - \usepackage[margin=.5in]{geometry}
   - \usepackage{float}
   - \usepackage{subfig}
   - \renewcommand{\thesubfigure}{\Alph{subfigure}}
   - \usepackage{chngpage}
---

```{r}
library(glue)
```



```{r, include = knitr::is_latex_output() & (startsWith(study_name, "Mock") | contain(tolower(data_cleaned), "mock"))}
knitr::asis_output("\\AddToShipoutPictureFG{
  \\AtPageCenter{
    \\makebox[0pt]{\\rotatebox[origin=c]{45}{
      \\scalebox{10}{\\texttransparent{0.3}{MOCK}}}}}}")
```



<!-- ```{r, include = knitr::is_latex_output() & (startsWith(study_name, "ENSEMBLE") & !contain(tolower(data_cleaned), "mock"))} -->
<!-- knitr::asis_output("\\AddToShipoutPictureFG{ -->
<!--   \\AtPageCenter{ -->
<!--     \\makebox[0pt]{\\rotatebox[origin=c]{45}{ -->
<!--       \\scalebox{10}{\\texttransparent{0.3}{Internal Use Only}}}}}}") -->
<!-- ``` -->



`r if (!is_ows_trial)'<!--'`

The data presented in the analysis are provided to NIAID in accordance with Clinical Trial Agreement between the parties. The study was funded in part by BARDA under Government Contract No. 75A50120C00034.



`r if (!is_ows_trial)'-->'`


<!-- `r if ( !( grepl("moderna", attr(config::get(config = Sys.getenv("TRIAL")), "config") ) ) )'<!--'` -->


<!-- * The data presented in the analysis originated from the Moderna Sponsored mRNA-1273-P301 clinical study and are provided to NIAID in accordance with Clinical Trial Agreement between the parties. The study was funded in part by BARDA under Government Contract No. 75A50120C00034 -->

<!-- * The preliminary immunogenicity data presented here do not reflect the Sponsors statistical analysis plan and therefore should not be interpreted as a protocol defined read-out of the clinical study. -->

<!-- * These data are not to be disclosed without written permission of Moderna. -->




