```{r, echo=FALSE, results='asis'}
if (!TRIAL %in% c("nextgen_mock")) { # some trials are organized differently, e.g. may have tables from two treatment arms together
  res = knitr::knit_child(c(here::here('cor_coxph', 'report_by_COR_coef.Rmd')), quiet = TRUE)
  cat(res, sep = '\n')
}
```


```{r, echo=FALSE, results='asis'}
if (show.ve.curves) {
  res = knitr::knit_child(c(here::here('cor_coxph', 'report_by_COR_curves.Rmd')), quiet = TRUE)
  cat(res, sep = '\n')
}
```


\clearpage
```{r, echo=FALSE, results='asis'}
if (TRIAL!='covail_frnt') { # skip trichotomized because hard to compare with id50 results
  cat(paste(concatList(rep('#',level+1)), "Trichotomized markers"))
  res = knitr::knit_child(c(here::here('cor_coxph', 'report_by_COR_tri.Rmd')), quiet = TRUE)
  cat(res, sep = '\n')
}
```


<!-- multiple_regression -->
```{r, echo=FALSE, results='asis'}
  tmp = config$multivariate_assays
  if (exists("multivariate_assays")) {
    tmp = multivariate_assays
  } 
  if (!is.null(tmp)) {
    cat("## Multivariate Cox Models of Risk\n\n")
    for (i in 1:length(tmp)) {
      res = knitr::knit_child(c(here::here('cor_coxph', 'multiple_regression.Rmd')), quiet = TRUE)
      cat(res, sep = '\n')
    }
  }
```






<!-- ## Additional content -->

<!-- \setlength{\tabcolsep}{.5ex} -->

<!-- \begin{longtable}{lcccccc} -->
<!-- \caption{Analysis of Day `r tpeak` markers (upper vs. lower tertile) as a CoR and a controlled risk CoP.}\\ -->
<!-- \hline -->
<!--   \multicolumn{1}{c}{} & \multicolumn{2}{c}{marginalized risk} & \multicolumn{2}{c}{controlled risk}     &  \multicolumn{1}{c}{}  & \multicolumn{1}{c}{} \\ -->
<!--   \multicolumn{1}{c}{} & \multicolumn{2}{c}{ratio $RR_M(0,1)$} & \multicolumn{2}{c}{ratio $RR_C(0,1)^1$} &  \multicolumn{2}{c}{e(0,1)$^2$} \\ -->
<!--   \multicolumn{1}{c}{} & Point Est. & 95\% CI                  & Point Est. & 95\% CI                    &   Point Est.  & 95\% CI UL \\ -->
<!-- \hline -->

<!--   \input{`r pathCoRoutput`/marginalized_risks_cat_`r fname.suffix`}\\ -->
<!--   \hline -->
<!-- \end{longtable} -->


<!-- $^1$Conservative (upper bound) estimate assuming unmeasured confounding at level $RR_{UD}(0,1)=RR_{EU}(0,1) = 2$ and thus $B(0,1)=4/3$.  -->

<!-- $^2$E-values are computed for upper tertile ($s=1$) vs. lower tertile ($s=0$) biomarker subgroups after controlling for `r covariates_adjusted`; UL = upper limit. -->




<!-- ```{r, echo=FALSE, results='asis'} -->
<!--   if (!is.null(config$additional_models)) { -->
<!--   cat("## Additional posthoc Cox Models of Risk") -->
<!--     for (i in 1:length(config$additional_models)) { -->
<!--       res = knitr::knit_child(c(here::here('cor_coxph', 'additional_model.Rmd')), quiet = TRUE) -->
<!--       cat(res, sep = '\n') -->
<!--     } -->
<!--   } -->
<!-- ``` -->


<!-- `r if (is.null(config$interaction)) '<!--'` -->
<!-- ## Interaction Cox Models of Risk -->

<!-- \begin{table}[H] -->
<!-- \centering -->
<!-- \input{`r pathCoRoutput`/CoR_itxn_multitesting} -->
<!-- \caption{ Inference for Day `r tpeak` antibody marker covariate-adjusted correlates of risk by Day \protect\input{`r pathCoRoutput`/timepoints_cum_risk_`r fname.suffix`} in the vaccine arm. Interaction P values. } -->
<!-- \end{table} -->

<!-- \clearpage -->
<!-- `r if (is.null(config$interaction)) '  <!--'` -->


<!-- ```{r, echo=FALSE, results='asis'} -->
<!-- if (!is.null(config$interaction)) { -->
<!--   for (ab in config$interaction) { -->
<!--       tmp=trim(strsplit(ab, " *\\* *")[[1]]) -->
<!--       a=tmp[1] -->
<!--       b=tmp[2] -->
<!--       res = knitr::knit_child(c(here::here('cor_coxph', 'itxn_by_assays.Rmd')), quiet = TRUE) -->
<!--       cat(res, sep = '\n') -->
<!--   } -->
<!-- } -->
<!-- ``` -->
