```{r, echo=FALSE, results='asis'}
if(is.null("fname.suffix")) fname.suffix = ''
```



<!-- ## Marginalized risk and controlled vaccine efficacy plots -->

<!-- \setlength{\tabcolsep}{.5ex} -->

<!-- \begin{longtable}{lcccccc} -->
<!-- \caption{Analysis of Day `r tpeak` markers (upper vs. lower tertile) as a CoR and a controlled risk CoP.}\\ -->
<!-- \hline -->
<!--   \multicolumn{1}{c}{} & \multicolumn{2}{c}{marginalized risk} & \multicolumn{2}{c}{controlled risk}     &  \multicolumn{1}{c}{}  & \multicolumn{1}{c}{} \\ -->
<!--   \multicolumn{1}{c}{} & \multicolumn{2}{c}{ratio $RR_M(0,1)$} & \multicolumn{2}{c}{ratio $RR_C(0,1)^1$} &  \multicolumn{2}{c}{e(0,1)$^2$} \\ -->
<!--   \multicolumn{1}{c}{} & Point Est. & 95\% CI                  & Point Est. & 95\% CI                    &   Point Est.  & 95\% CI UL \\ -->
<!-- \hline -->

<!--   \input{`r pathCoRoutput`/marginalized_risks_cat_`r fname.suffix`}\\ -->
<!--   \hline -->
<!-- \end{longtable} -->


<!-- $^1$Conservative (upper bound) estimate assuming unmeasured confounding at level $RR_{UD}(0,1)=RR_{EU}(0,1) = 2$ and thus $B(0,1)=4/3$.  -->

<!-- $^2$E-values are computed for upper tertile ($s=1$) vs. lower tertile ($s=0$) biomarker subgroups after controlling for `r covariates_adjusted`; UL = upper limit. -->

<!-- `r special.note` -->





```{r, echo=FALSE, results='asis'}
  for (a in all.markers) {
    assay=marker.name.to.assay(a)
    res = knitr::knit_child(c(here::here('cor_coxph', 'risk_plots_by_assays.Rmd')), quiet = TRUE)
    cat(res, sep = '\n')
  }
```

