```{r, echo=FALSE, message=FALSE}
message("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ running cop_binaryprinstrat report ~~~~~~~~~~~~~~~~~~~~~~~~~")
```

`r 
tt=timepoints
`


```{r, echo=FALSE, results='asis'}

covariates_adjusted = covariates_riskscore
covariates_adjusted = sub("\\~\\.\\+","",covariates_adjusted)
covariates_adjusted = sub("_","",covariates_adjusted)

if(file.exists(here::here('cop_binaryprinstrat', paste0('report_', tolower(study_name), '.Rmd')))) {
  
  message ("trial-specific report rmd found")
  res = knitr::knit_child(c(here::here('cop_binaryprinstrat', paste0('report_', tolower(study_name), '.Rmd'))), quiet = TRUE)
  cat(res, sep = '\n')

} else {

  for (tpeak in tt) {
    COR <- paste0("D", tpeak)
    config.cor <- config::get(config = COR)
    for(opt in names(config.cor)) eval(parse(text = paste0(names(config.cor[opt])," <- config.cor[[opt]]")))
    special.note = ""
    pathCoRoutput <- paste0("cop_binaryprinstrat/output/", attr(config,"config"), "/", COR)
    res = knitr::knit_child(c(here::here('cop_binaryprinstrat', 'report_sub.Rmd')), quiet = TRUE)
    cat(res, sep = '\n')
  }

}
```
